<?php

use Illuminate\Database\Seeder;

class CategoryLocationTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $category = [
          ['category_no' => 11001,	'category' => '농/묘'],
          ['category_no' => 11002,	'category' => '유적터'],
          ['category_no' => 11003,	'category' => '사적/명승지'],
          ['category_no' => 11004,	'category' => '동물/식물/광물 기념물'],
          ['category_no' => 11005,	'category' => '기타'],
          ['category_no' => 12001,	'category' => '고궁'],
          ['category_no' => 12002,	'category' => '성/성곽/문'],
          ['category_no' => 12003,	'category' => '탑/비'],
          ['category_no' => 13001,	'category' => '고택/고건축'],
          ['category_no' => 13002,	'category' => '정자'],
          ['category_no' => 13003,	'category' => '사당'],
          ['category_no' => 13004,	'category' => '향교'],
          ['category_no' => 13005,	'category' => '민속마을'],
          ['category_no' => 13006,	'category' => '전통놀이'],
          ['category_no' => 13007,	'category' => '기타'],
          ['category_no' => 21001,	'category' => '산'],
          ['category_no' => 21002,	'category' => '들'],
          ['category_no' => 21003,	'category' => '숲'],
          ['category_no' => 21004,	'category' => '바다'],
          ['category_no' => 21005,	'category' => '섬'],
          ['category_no' => 21006,	'category' => '둔치'],
          ['category_no' => 21007,	'category' => '계곡/폭포'],
          ['category_no' => 21008,	'category' => '강/하천'],
          ['category_no' => 21009,	'category' => '갯벌'],
          ['category_no' => 21010,	'category' => '호수/저수지'],
          ['category_no' => 21011,	'category' => '동굴'],
          ['category_no' => 21012,	'category' => '약수터'],
          ['category_no' => 21013,	'category' => '낚시터'],
          ['category_no' => 21014,	'category' => '기타'],
          ['category_no' => 22001,	'category' => '건물'],
          ['category_no' => 22002,	'category' => '야경'],
          ['category_no' => 22003,	'category' => '전경'],
          ['category_no' => 22004,	'category' => '번화가'],
          ['category_no' => 22005,	'category' => '공터'],
          ['category_no' => 22006,	'category' => '광장'],
          ['category_no' => 22007,	'category' => '기타'],
          ['category_no' => 23001,	'category' => '과수원'],
          ['category_no' => 23002,	'category' => '목장'],
          ['category_no' => 23003,	'category' => '화훼단지'],
          ['category_no' => 23004,	'category' => '임야'],
          ['category_no' => 23005,	'category' => '간적지'],
          ['category_no' => 23006,	'category' => '축사'],
          ['category_no' => 23007,	'category' => '가축시장'],
          ['category_no' => 23008,	'category' => '도축장/도계장'],
          ['category_no' => 23009,	'category' => '종묘배양시설'],
          ['category_no' => 23010,	'category' => '버섯재배사'],
          ['category_no' => 23011,	'category' => '온실'],
          ['category_no' => 23012,	'category' => '양수장'],
          ['category_no' => 23013,	'category' => '양식장'],
          ['category_no' => 23014,	'category' => '등대'],
          ['category_no' => 23015,	'category' => '방파제'],
          ['category_no' => 23016,	'category' => '염전'],
          ['category_no' => 23017,	'category' => '기타'],
          ['category_no' => 31001,	'category' => '공연장'],
          ['category_no' => 31002,	'category' => '집회장'],
          ['category_no' => 31003,	'category' => '관람장'],
          ['category_no' => 31004,	'category' => '전시장'],
          ['category_no' => 31005,	'category' => '기타'],
          ['category_no' => 32001,	'category' => '야외음악당'],
          ['category_no' => 32002,	'category' => '야외극장'],
          ['category_no' => 32003,	'category' => '관망탑'],
          ['category_no' => 32004,	'category' => '휴게소'],
          ['category_no' => 32005,	'category' => '휴게음식점'],
          ['category_no' => 32006,	'category' => '공원'],
          ['category_no' => 32007,	'category' => '유원지'],
          ['category_no' => 32008,	'category' => '휴양림'],
          ['category_no' => 32009,	'category' => '동/식물원'],
          ['category_no' => 32010,	'category' => '수족관'],
          ['category_no' => 32011,	'category' => '기타'],
          ['category_no' => 33001,	'category' => '종교집회장'],
          ['category_no' => 33002,	'category' => '종교집회장 내 납골당'],
          ['category_no' => 33003,	'category' => '기타'],
          ['category_no' => 41001,	'category' => '학교'],
          ['category_no' => 41002,	'category' => '교육원/수련원/연수원'],
          ['category_no' => 41003,	'category' => '직업훈련소'],
          ['category_no' => 41004,	'category' => '연구소/실험실'],
          ['category_no' => 41005,	'category' => '도서관'],
          ['category_no' => 41006,	'category' => '학원'],
          ['category_no' => 41007,	'category' => '폐교'],
          ['category_no' => 41008,	'category' => '교육청'],
          ['category_no' => 41009,	'category' => '기타'],
          ['category_no' => 42001,	'category' => '병원'],
          ['category_no' => 42002,	'category' => '한의원'],
          ['category_no' => 42003,	'category' => '격리병원/요양원'],
          ['category_no' => 42004,	'category' => '장례식장'],
          ['category_no' => 42005,	'category' => '화장장'],
          ['category_no' => 42006,	'category' => '납골당'],
          ['category_no' => 42007,	'category' => '묘지에 부수되는 건축물'],
          ['category_no' => 42008,	'category' => '묘지에 부수되는 건축물'],
          ['category_no' => 42009,	'category' => '보건소'],
          ['category_no' => 42010,	'category' => '기타'],
          ['category_no' => 43001,	'category' => '아동복지시설'],
          ['category_no' => 43002,	'category' => '노인복지시설'],
          ['category_no' => 43003,	'category' => '기타 사회복지시설'],
          ['category_no' => 43004,	'category' => '기타'],
          ['category_no' => 51001,	'category' => '국회'],
          ['category_no' => 51002,	'category' => '의회'],
          ['category_no' => 51003,	'category' => '시/군청'],
          ['category_no' => 51004,	'category' => '주민센터'],
          ['category_no' => 51005,	'category' => '세무서'],
          ['category_no' => 51006,	'category' => '구청'],
          ['category_no' => 51007,	'category' => '기타'],
          ['category_no' => 52001,	'category' => '법원'],
          ['category_no' => 52002,	'category' => '검찰청'],
          ['category_no' => 52003,	'category' => '경찰서'],
          ['category_no' => 52004,	'category' => '지구대'],
          ['category_no' => 52005,	'category' => '경찰관련시설'],
          ['category_no' => 52006,	'category' => '치안센터'],
          ['category_no' => 52007,	'category' => '기타'],
          ['category_no' => 53001,	'category' => '소방서'],
          ['category_no' => 53002,	'category' => '소방학교'],
          ['category_no' => 53003,	'category' => '소방시설'],
          ['category_no' => 53004,	'category' => '교도소'],
          ['category_no' => 53005,	'category' => '감화원'],
          ['category_no' => 53006,	'category' => '구치소'],
          ['category_no' => 53007,	'category' => '소년원'],
          ['category_no' => 53008,	'category' => '교정관련시설'],
          ['category_no' => 53009,	'category' => '군부대'],
          ['category_no' => 53010,	'category' => '훈련장'],
          ['category_no' => 53011,	'category' => '훈련소'],
          ['category_no' => 53012,	'category' => '기타'],
          ['category_no' => 54001,	'category' => '문화원'],
          ['category_no' => 54002,	'category' => '우편관련시설'],
          ['category_no' => 54003,	'category' => '마을회관'],
          ['category_no' => 54004,	'category' => '구민회관'],
          ['category_no' => 54005,	'category' => '예술회관'],
          ['category_no' => 54006,	'category' => '대사관'],
          ['category_no' => 54007,	'category' => '청소년회관'],
          ['category_no' => 54008,	'category' => '기타'],
          ['category_no' => 61001,	'category' => '주택'],
          ['category_no' => 61002,	'category' => '단독주택'],
          ['category_no' => 61003,	'category' => '다중주택'],
          ['category_no' => 61004,	'category' => '다가구주택'],
          ['category_no' => 61005,	'category' => '아파트'],
          ['category_no' => 61006,	'category' => '연립주택'],
          ['category_no' => 61007,	'category' => '다세대주택'],
          ['category_no' => 61008,	'category' => '빌라'],
          ['category_no' => 61009,	'category' => '기숙사'],
          ['category_no' => 61010,	'category' => '주택가 골목길'],
          ['category_no' => 61011,	'category' => '탄광촌 등 기타 특수촌'],
          ['category_no' => 61012,	'category' => '기타'],
          ['category_no' => 62001,	'category' => '사무실'],
          ['category_no' => 62002,	'category' => '회의실'],
          ['category_no' => 62003,	'category' => '사장실'],
          ['category_no' => 62004,	'category' => '접견실'],
          ['category_no' => 62005,	'category' => '기타 건물내무'],
          ['category_no' => 62006,	'category' => '기타'],
          ['category_no' => 63001,	'category' => '일반음식점'],
          ['category_no' => 63002,	'category' => '기원'],
          ['category_no' => 63003,	'category' => '서점'],
          ['category_no' => 63004,	'category' => '사진관'],
          ['category_no' => 63005,	'category' => '금융시설'],
          ['category_no' => 63006,	'category' => '이용원/미용원'],
          ['category_no' => 63007,	'category' => '목욕시설/온천'],
          ['category_no' => 63008,	'category' => '노래연습장'],
          ['category_no' => 63009,	'category' => '대장간'],
          ['category_no' => 63010,	'category' => '방앗간'],
          ['category_no' => 63011,	'category' => '정미소'],
          ['category_no' => 63012,	'category' => '카페'],
          ['category_no' => 63013,	'category' => '결혼식장'],
          ['category_no' => 63014,	'category' => '기타'],
          ['category_no' => 64001,	'category' => '단란주점'],
          ['category_no' => 64002,	'category' => '주점영업'],
          ['category_no' => 64003,	'category' => '유원시설업'],
          ['category_no' => 64004,	'category' => '투전기/카지노업소'],
          ['category_no' => 64005,	'category' => '무도장/무도학원'],
          ['category_no' => 64006,	'category' => '도/소매시장'],
          ['category_no' => 64007,	'category' => '백화점'],
          ['category_no' => 64008,	'category' => '대형마트'],
          ['category_no' => 64009,	'category' => '상점'],
          ['category_no' => 64010,	'category' => '지하상가'],
          ['category_no' => 64011,	'category' => '슈퍼마켓'],
          ['category_no' => 64012,	'category' => '편의점'],
          ['category_no' => 64013,	'category' => '위락시설'],
          ['category_no' => 64014,	'category' => '기타'],
          ['category_no' => 65001,	'category' => '체육관'],
          ['category_no' => 65002,	'category' => '운동장'],
          ['category_no' => 65003,	'category' => '구기종목 경기장'],
          ['category_no' => 65004,	'category' => '조정/요트경기장'],
          ['category_no' => 65005,	'category' => '스키장'],
          ['category_no' => 65006,	'category' => '골프장/연습장'],
          ['category_no' => 65007,	'category' => '양궁장'],
          ['category_no' => 65008,	'category' => '스킨스쿠버'],
          ['category_no' => 65009,	'category' => '도장/체육공원'],
          ['category_no' => 65010,	'category' => '수영장'],
          ['category_no' => 65011,	'category' => '경마'],
          ['category_no' => 65012,	'category' => '경륜장'],
          ['category_no' => 65013,	'category' => '종합스포츠'],
          ['category_no' => 65014,	'category' => '아이스링크'],
          ['category_no' => 65015,	'category' => '기타'],
          ['category_no' => 66001,	'category' => '호텔'],
          ['category_no' => 66002,	'category' => '콘도'],
          ['category_no' => 66003,	'category' => '유스호스텔'],
          ['category_no' => 66004,	'category' => '모텔'],
          ['category_no' => 66005,	'category' => '여관'],
          ['category_no' => 66006,	'category' => '팬션'],
          ['category_no' => 66007,	'category' => '민박'],
          ['category_no' => 66008,	'category' => '오두막/방갈로'],
          ['category_no' => 66009,	'category' => '여인숙'],
          ['category_no' => 66010,	'category' => '기타'],
          ['category_no' => 71001,	'category' => '물품 제조/가공/수리 관련 시설'],
          ['category_no' => 71002,	'category' => '가내공업'],
          ['category_no' => 71003,	'category' => '창고'],
          ['category_no' => 71004,	'category' => '하역장'],
          ['category_no' => 71005,	'category' => '폐공장'],
          ['category_no' => 71006,	'category' => '기타'],
          ['category_no' => 72001,	'category' => '주유소/석유판매소'],
          ['category_no' => 72002,	'category' => '액화석유가스충전소'],
          ['category_no' => 72003,	'category' => '액화가스취급소/판매소'],
          ['category_no' => 72004,	'category' => '위험물 제조소/저장소/취급소'],
          ['category_no' => 72005,	'category' => '분뇨폐기물'],
          ['category_no' => 72006,	'category' => '처리시설'],
          ['category_no' => 72007,	'category' => '폐기물 재활용시설'],
          ['category_no' => 72008,	'category' => '고물상'],
          ['category_no' => 72009,	'category' => '정수시설'],
          ['category_no' => 72010,	'category' => '기타'],
          ['category_no' => 73001,	'category' => '방송국'],
          ['category_no' => 73002,	'category' => '전신전화국'],
          ['category_no' => 73003,	'category' => '통신용시설'],
          ['category_no' => 73004,	'category' => '신문사'],
          ['category_no' => 73005,	'category' => '수력/풍력/화력발전소'],
          ['category_no' => 73006,	'category' => '전기시설물'],
          ['category_no' => 73007,	'category' => '댐'],
          ['category_no' => 73008,	'category' => '기타'],
          ['category_no' => 81001,	'category' => '일반도로'],
          ['category_no' => 81002,	'category' => '지하차도'],
          ['category_no' => 81003,	'category' => '터널'],
          ['category_no' => 81004,	'category' => '나들목'],
          ['category_no' => 81005,	'category' => '비포장로'],
          ['category_no' => 81006,	'category' => '교차로'],
          ['category_no' => 81007,	'category' => '건널목'],
          ['category_no' => 81008,	'category' => '톨게이트'],
          ['category_no' => 81009,	'category' => '다리/교각'],
          ['category_no' => 81010,	'category' => '굴다리'],
          ['category_no' => 81011,	'category' => '임시주정차'],
          ['category_no' => 81012,	'category' => '기타'],
          ['category_no' => 82001,	'category' => '인도'],
          ['category_no' => 82002,	'category' => '육교'],
          ['category_no' => 82003,	'category' => '지하도'],
          ['category_no' => 82004,	'category' => '등산로'],
          ['category_no' => 82005,	'category' => '산책로'],
          ['category_no' => 82006,	'category' => '자전거도로'],
          ['category_no' => 82007,	'category' => '계단'],
          ['category_no' => 82008,	'category' => '기타'],
          ['category_no' => 83001,	'category' => '터미널'],
          ['category_no' => 83002,	'category' => '택시승강장'],
          ['category_no' => 83003,	'category' => '버스정류장'],
          ['category_no' => 83004,	'category' => '지하철/철도역사'],
          ['category_no' => 83005,	'category' => '차량기지'],
          ['category_no' => 83006,	'category' => '공항시설'],
          ['category_no' => 83007,	'category' => '헬기장'],
          ['category_no' => 83008,	'category' => '항만/여객시설'],
          ['category_no' => 83009,	'category' => '집배송시설'],
          ['category_no' => 83010,	'category' => '철도시설물'],
          ['category_no' => 83011,	'category' => '차고/주차장/주기장'],
          ['category_no' => 83012,	'category' => '세차장'],
          ['category_no' => 83013,	'category' => '폐차장'],
          ['category_no' => 83014,	'category' => '검사장'],
          ['category_no' => 83015,	'category' => '매매장'],
          ['category_no' => 83016,	'category' => '정비공장'],
          ['category_no' => 83017,	'category' => '운전학원'],
          ['category_no' => 83018,	'category' => '정비학원'],
          ['category_no' => 83019,	'category' => '면허시험장'],
          ['category_no' => 83020,	'category' => '기타'],
        ];

        DB::table('category_locations')->insert($category);
    }
}
