<?php

use Illuminate\Database\Seeder;

class DramaEmployeeTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $employee=[
          ['drama_no' => 1,	'sequence' => 1,	'team_no' => 1,	'user_no' => 7,	'position_no' => 3000, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 1,	'sequence' => 2,	'team_no' => 1,	'user_no' => 59,	'position_no' => 1040, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 1,	'sequence' => 3,	'team_no' => 9,	'user_no' => 1,	'position_no' => 2000, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 1,	'sequence' => 4,	'team_no' => 9,	'user_no' => 3,	'position_no' => 2000, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 1,	'sequence' => 5,	'team_no' => 9,	'user_no' => 4,	'position_no' => 2000, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 1,	'sequence' => 6,	'team_no' => 7,	'user_no' => 8,	'position_no' => 3030, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 1,	'sequence' => 7,	'team_no' => 7,	'user_no' => 9,	'position_no' => 3031, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 1,	'sequence' => 8,	'team_no' => 2,	'user_no' => 10,	'position_no' => 3901, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 1,	'sequence' => 9,	'team_no' => 6,	'user_no' => 49,	'position_no' => 3091, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 1,	'sequence' => 10,	'team_no' => 2,	'user_no' => 33,	'position_no' => 3900, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 1,	'sequence' => 11,	'team_no' => 10,	'user_no' => 57,	'position_no' => 2002, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 1,	'sequence' => 12,	'team_no' => 9,	'user_no' => 100,	'position_no' => 2000, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 1,	'sequence' => 13,	'team_no' => 9,	'user_no' => 101,	'position_no' => 2000, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 1,	'sequence' => 14,	'team_no' => 9,	'user_no' => 102,	'position_no' => 2001, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 1,	'sequence' => 15,	'team_no' => 9,	'user_no' => 103,	'position_no' => 2001, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 1,	'sequence' => 16,	'team_no' => 9,	'user_no' => 108,	'position_no' => 2001, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 1,	'sequence' => 17,	'team_no' => 9,	'user_no' => 109,	'position_no' => 2001, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 1,	'sequence' => 18,	'team_no' => 9,	'user_no' => 110,	'position_no' => 2002, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 1,	'sequence' => 19,	'team_no' => 9,	'user_no' => 111,	'position_no' => 2002, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 1,	'sequence' => 20,	'team_no' => 10,	'user_no' => 112,	'position_no' => 2002, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 1,	'sequence' => 21,	'team_no' => 10,	'user_no' => 113,	'position_no' => 2002, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 1,	'sequence' => 22,	'team_no' => 10,	'user_no' => 114,	'position_no' => 2002, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 1,	'sequence' => 23,	'team_no' => 10,	'user_no' => 115,	'position_no' => 2002, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 1,	'sequence' => 24,	'team_no' => 10,	'user_no' => 116,	'position_no' => 2002, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 1,	'sequence' => 25,	'team_no' => 10,	'user_no' => 117,	'position_no' => 2002, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 2,	'sequence' => 13,	'team_no' => 1,	'user_no' => 48,	'position_no' => 1030, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 2,	'sequence' => 14,	'team_no' => 7,	'user_no' => 12,	'position_no' => 3030, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 2,	'sequence' => 15,	'team_no' => 1,	'user_no' => 17,	'position_no' => 1040, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 2,	'sequence' => 16,	'team_no' => 9,	'user_no' => 2,	'position_no' => 2000, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 2,	'sequence' => 17,	'team_no' => 9,	'user_no' => 40,	'position_no' => 2000, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 2,	'sequence' => 18,	'team_no' => 6,	'user_no' => 50,	'position_no' => 3091, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 2,	'sequence' => 19,	'team_no' => 2,	'user_no' => 33,	'position_no' => 3900, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 2,	'sequence' => 20,	'team_no' => 1,	'user_no' => 26,	'position_no' => 3011, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 2,	'sequence' => 21,	'team_no' => 1,	'user_no' => 27,	'position_no' => 3011, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 3,	'sequence' => 22,	'team_no' => 1,	'user_no' => 6,	'position_no' => 1030, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 3,	'sequence' => 23,	'team_no' => 1,	'user_no' => 16,	'position_no' => 1040, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 3,	'sequence' => 24,	'team_no' => 2,	'user_no' => 33,	'position_no' => 3090, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 3,	'sequence' => 25,	'team_no' => 4,	'user_no' => 21,	'position_no' => 3040, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 3,	'sequence' => 26,	'team_no' => 9,	'user_no' => 5,	'position_no' => 2000, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 3,	'sequence' => 27,	'team_no' => 9,	'user_no' => 43,	'position_no' => 2000, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 3,	'sequence' => 28,	'team_no' => 9,	'user_no' => 44,	'position_no' => 2000, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 3,	'sequence' => 29,	'team_no' => 6,	'user_no' => 34,	'position_no' => 3090, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 3,	'sequence' => 30,	'team_no' => 2,	'user_no' => 36,	'position_no' => 3903, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 3,	'sequence' => 31,	'team_no' => 7,	'user_no' => 19,	'position_no' => 3080, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 3,	'sequence' => 32,	'team_no' => 2,	'user_no' => 11,	'position_no' => 3901, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 3,	'sequence' => 33,	'team_no' => 7,	'user_no' => 13,	'position_no' => 3021, 'created_at' => date("Y-m-d H:i:s") ],
          ['drama_no' => 1,	'sequence' => 27,	'team_no' => 9,	'user_no' => 141,	'position_no' => 2001,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 28,	'team_no' => 10,	'user_no' => 152,	'position_no' => 2002,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 29,	'team_no' => 10,	'user_no' => 160,	'position_no' => 2002,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 30,	'team_no' => 9,	'user_no' => 142,	'position_no' => 2001,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 31,	'team_no' => 9,	'user_no' => 154,	'position_no' => 2001,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 32,	'team_no' => 10,	'user_no' => 144,	'position_no' => 2002,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 33,	'team_no' => 9,	'user_no' => 132,	'position_no' => 2001,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 34,	'team_no' => 9,	'user_no' => 151,	'position_no' => 2001,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 35,	'team_no' => 9,	'user_no' => 143,	'position_no' => 2001,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 36,	'team_no' => 9,	'user_no' => 145,	'position_no' => 2001,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 37,	'team_no' => 9,	'user_no' => 140,	'position_no' => 2001,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 38,	'team_no' => 9,	'user_no' => 164,	'position_no' => 2001,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 39,	'team_no' => 9,	'user_no' => 158,	'position_no' => 2001,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 40,	'team_no' => 10,	'user_no' => 131,	'position_no' => 2002,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 41,	'team_no' => 9,	'user_no' => 147,	'position_no' => 2001,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 42,	'team_no' => 9,	'user_no' => 175,	'position_no' => 2001,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 4,	'sequence' => 1,	'team_no' => 1,	'user_no' => 180,	'position_no' => 1030,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 4,	'sequence' => 2,	'team_no' => 1,	'user_no' => 260,	'position_no' => 1040,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 4,	'sequence' => 3,	'team_no' => 7,	'user_no' => 203,	'position_no' => 3020,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 4,	'sequence' => 4,	'team_no' => 7,	'user_no' => 220,	'position_no' => 3030,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 5,	'sequence' => 1,	'team_no' => 1,	'user_no' => 182,	'position_no' => 1030,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 5,	'sequence' => 2,	'team_no' => 1,	'user_no' => 261,	'position_no' => 1040,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 5,	'sequence' => 3,	'team_no' => 7,	'user_no' => 200,	'position_no' => 3020,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 5,	'sequence' => 4,	'team_no' => 7,	'user_no' => 223,	'position_no' => 3030,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 6,	'sequence' => 1,	'team_no' => 1,	'user_no' => 181,	'position_no' => 1030,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 6,	'sequence' => 2,	'team_no' => 1,	'user_no' => 263,	'position_no' => 1040,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 6,	'sequence' => 3,	'team_no' => 7,	'user_no' => 201,	'position_no' => 3020,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 6,	'sequence' => 4,	'team_no' => 7,	'user_no' => 222,	'position_no' => 3030,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 7,	'sequence' => 1,	'team_no' => 1,	'user_no' => 183,	'position_no' => 1030,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 7,	'sequence' => 2,	'team_no' => 1,	'user_no' => 262,	'position_no' => 1040,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 7,	'sequence' => 3,	'team_no' => 7,	'user_no' => 202,	'position_no' => 3020,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 7,	'sequence' => 4,	'team_no' => 7,	'user_no' => 221,	'position_no' => 3030,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 4,	'sequence' => 5,	'team_no' => 1,	'user_no' => 280,	'position_no' => 3901,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 5,	'sequence' => 5,	'team_no' => 1,	'user_no' => 282,	'position_no' => 3901,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 6,	'sequence' => 5,	'team_no' => 1,	'user_no' => 281,	'position_no' => 3901,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 7,	'sequence' => 5,	'team_no' => 1,	'user_no' => 283,	'position_no' => 3901,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 4,	'sequence' => 6,	'team_no' => 1,	'user_no' => 337,	'position_no' => 3900,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 5,	'sequence' => 6,	'team_no' => 1,	'user_no' => 338,	'position_no' => 3900,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 6,	'sequence' => 6,	'team_no' => 1,	'user_no' => 335,	'position_no' => 3900,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 7,	'sequence' => 6,	'team_no' => 1,	'user_no' => 336,	'position_no' => 3900,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 8,	'sequence' => 1,	'team_no' => 1,	'user_no' => 184,	'position_no' => 1030,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 8,	'sequence' => 2,	'team_no' => 1,	'user_no' => 264,	'position_no' => 1040,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 8,	'sequence' => 3,	'team_no' => 1,	'user_no' => 278,	'position_no' => 1040,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 8,	'sequence' => 4,	'team_no' => 1,	'user_no' => 284,	'position_no' => 3901,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 8,	'sequence' => 5,	'team_no' => 6,	'user_no' => 290,	'position_no' => 3090,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 8,	'sequence' => 6,	'team_no' => 4,	'user_no' => 300,	'position_no' => 3040,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 8,	'sequence' => 7,	'team_no' => 6,	'user_no' => 315,	'position_no' => 3091,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 8,	'sequence' => 8,	'team_no' => 8,	'user_no' => 325,	'position_no' => 3100,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 8,	'sequence' => 9,	'team_no' => 1,	'user_no' => 334,	'position_no' => 3903,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 8,	'sequence' => 10,	'team_no' => 7,	'user_no' => 224,	'position_no' => 3030,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 8,	'sequence' => 11,	'team_no' => 7,	'user_no' => 204,	'position_no' => 3020,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 9,	'sequence' => 1,	'team_no' => 1,	'user_no' => 185,	'position_no' => 1030,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 10,	'sequence' => 1,	'team_no' => 1,	'user_no' => 186,	'position_no' => 1030,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 11,	'sequence' => 1,	'team_no' => 1,	'user_no' => 187,	'position_no' => 1030,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 12,	'sequence' => 1,	'team_no' => 1,	'user_no' => 188,	'position_no' => 1030,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 13,	'sequence' => 1,	'team_no' => 1,	'user_no' => 189,	'position_no' => 1030,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 14,	'sequence' => 1,	'team_no' => 1,	'user_no' => 190,	'position_no' => 1030,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 15,	'sequence' => 1,	'team_no' => 1,	'user_no' => 191,	'position_no' => 1030,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 9,	'sequence' => 2,	'team_no' => 7,	'user_no' => 205,	'position_no' => 3020,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 10,	'sequence' => 2,	'team_no' => 7,	'user_no' => 206,	'position_no' => 3020,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 11,	'sequence' => 2,	'team_no' => 7,	'user_no' => 207,	'position_no' => 3020,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 12,	'sequence' => 2,	'team_no' => 7,	'user_no' => 208,	'position_no' => 3020,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 13,	'sequence' => 2,	'team_no' => 7,	'user_no' => 209,	'position_no' => 3020,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 14,	'sequence' => 2,	'team_no' => 7,	'user_no' => 210,	'position_no' => 3020,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 15,	'sequence' => 2,	'team_no' => 7,	'user_no' => 211,	'position_no' => 3020,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 9,	'sequence' => 3,	'team_no' => 7,	'user_no' => 225,	'position_no' => 3030,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 10,	'sequence' => 3,	'team_no' => 7,	'user_no' => 226,	'position_no' => 3030,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 11,	'sequence' => 3,	'team_no' => 7,	'user_no' => 227,	'position_no' => 3030,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 12,	'sequence' => 3,	'team_no' => 7,	'user_no' => 228,	'position_no' => 3030,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 13,	'sequence' => 3,	'team_no' => 7,	'user_no' => 229,	'position_no' => 3030,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 14,	'sequence' => 3,	'team_no' => 7,	'user_no' => 230,	'position_no' => 3030,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 15,	'sequence' => 3,	'team_no' => 7,	'user_no' => 231,	'position_no' => 3030,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 9,	'sequence' => 4,	'team_no' => 2,	'user_no' => 240,	'position_no' => 3080,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 10,	'sequence' => 4,	'team_no' => 2,	'user_no' => 241,	'position_no' => 3080,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 11,	'sequence' => 4,	'team_no' => 2,	'user_no' => 242,	'position_no' => 3080,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 12,	'sequence' => 4,	'team_no' => 2,	'user_no' => 243,	'position_no' => 3080,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 13,	'sequence' => 4,	'team_no' => 2,	'user_no' => 244,	'position_no' => 3080,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 14,	'sequence' => 4,	'team_no' => 2,	'user_no' => 245,	'position_no' => 3080,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 15,	'sequence' => 4,	'team_no' => 2,	'user_no' => 246,	'position_no' => 3080,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 9,	'sequence' => 5,	'team_no' => 1,	'user_no' => 265,	'position_no' => 1040,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 10,	'sequence' => 5,	'team_no' => 1,	'user_no' => 266,	'position_no' => 1040,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 11,	'sequence' => 5,	'team_no' => 1,	'user_no' => 267,	'position_no' => 1040,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 12,	'sequence' => 5,	'team_no' => 1,	'user_no' => 268,	'position_no' => 1040,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 13,	'sequence' => 5,	'team_no' => 1,	'user_no' => 269,	'position_no' => 1040,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 14,	'sequence' => 5,	'team_no' => 1,	'user_no' => 270,	'position_no' => 1040,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 15,	'sequence' => 5,	'team_no' => 1,	'user_no' => 271,	'position_no' => 1040,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 9,	'sequence' => 6,	'team_no' => 1,	'user_no' => 272,	'position_no' => 1040,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 10,	'sequence' => 6,	'team_no' => 1,	'user_no' => 273,	'position_no' => 1040,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 11,	'sequence' => 6,	'team_no' => 1,	'user_no' => 274,	'position_no' => 1040,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 12,	'sequence' => 6,	'team_no' => 1,	'user_no' => 275,	'position_no' => 1040,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 13,	'sequence' => 6,	'team_no' => 1,	'user_no' => 276,	'position_no' => 1040,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 14,	'sequence' => 6,	'team_no' => 1,	'user_no' => 277,	'position_no' => 1040,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 15,	'sequence' => 6,	'team_no' => 1,	'user_no' => 279,	'position_no' => 1040,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 9,	'sequence' => 7,	'team_no' => 6,	'user_no' => 291,	'position_no' => 3090,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 10,	'sequence' => 7,	'team_no' => 6,	'user_no' => 292,	'position_no' => 3090,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 11,	'sequence' => 7,	'team_no' => 6,	'user_no' => 293,	'position_no' => 3090,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 12,	'sequence' => 7,	'team_no' => 6,	'user_no' => 294,	'position_no' => 3090,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 13,	'sequence' => 7,	'team_no' => 6,	'user_no' => 295,	'position_no' => 3090,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 14,	'sequence' => 7,	'team_no' => 6,	'user_no' => 296,	'position_no' => 3090,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 15,	'sequence' => 7,	'team_no' => 6,	'user_no' => 297,	'position_no' => 3090,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 9,	'sequence' => 8,	'team_no' => 4,	'user_no' => 301,	'position_no' => 3040,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 10,	'sequence' => 8,	'team_no' => 4,	'user_no' => 302,	'position_no' => 3040,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 11,	'sequence' => 8,	'team_no' => 4,	'user_no' => 303,	'position_no' => 3040,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 12,	'sequence' => 8,	'team_no' => 4,	'user_no' => 304,	'position_no' => 3040,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 13,	'sequence' => 8,	'team_no' => 4,	'user_no' => 305,	'position_no' => 3040,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 14,	'sequence' => 8,	'team_no' => 4,	'user_no' => 306,	'position_no' => 3040,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 15,	'sequence' => 8,	'team_no' => 4,	'user_no' => 307,	'position_no' => 3040,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 9,	'sequence' => 9,	'team_no' => 6,	'user_no' => 316,	'position_no' => 3091,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 10,	'sequence' => 9,	'team_no' => 6,	'user_no' => 317,	'position_no' => 3091,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 11,	'sequence' => 9,	'team_no' => 6,	'user_no' => 318,	'position_no' => 3091,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 12,	'sequence' => 9,	'team_no' => 6,	'user_no' => 319,	'position_no' => 3091,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 13,	'sequence' => 9,	'team_no' => 6,	'user_no' => 320,	'position_no' => 3091,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 14,	'sequence' => 9,	'team_no' => 6,	'user_no' => 321,	'position_no' => 3091,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 15,	'sequence' => 9,	'team_no' => 6,	'user_no' => 322,	'position_no' => 3091,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 9,	'sequence' => 10,	'team_no' => 7,	'user_no' => 212,	'position_no' => 3021,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 10,	'sequence' => 10,	'team_no' => 7,	'user_no' => 213,	'position_no' => 3021,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 11,	'sequence' => 10,	'team_no' => 7,	'user_no' => 214,	'position_no' => 3021,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 12,	'sequence' => 10,	'team_no' => 7,	'user_no' => 215,	'position_no' => 3021,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 13,	'sequence' => 10,	'team_no' => 7,	'user_no' => 216,	'position_no' => 3021,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 14,	'sequence' => 10,	'team_no' => 7,	'user_no' => 217,	'position_no' => 3021,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 15,	'sequence' => 10,	'team_no' => 7,	'user_no' => 218,	'position_no' => 3021,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 9,	'sequence' => 11,	'team_no' => 1,	'user_no' => 192,	'position_no' => 3011,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 10,	'sequence' => 11,	'team_no' => 1,	'user_no' => 193,	'position_no' => 3011,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 11,	'sequence' => 11,	'team_no' => 1,	'user_no' => 194,	'position_no' => 3011,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 12,	'sequence' => 11,	'team_no' => 1,	'user_no' => 195,	'position_no' => 3011,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 13,	'sequence' => 11,	'team_no' => 1,	'user_no' => 196,	'position_no' => 3011,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 14,	'sequence' => 11,	'team_no' => 1,	'user_no' => 197,	'position_no' => 3011,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 15,	'sequence' => 11,	'team_no' => 1,	'user_no' => 198,	'position_no' => 3011,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 9,	'sequence' => 12,	'team_no' => 9,	'user_no' => 120,	'position_no' => 2000,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 10,	'sequence' => 12,	'team_no' => 9,	'user_no' => 121,	'position_no' => 2000,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 11,	'sequence' => 12,	'team_no' => 9,	'user_no' => 122,	'position_no' => 2000,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 12,	'sequence' => 12,	'team_no' => 9,	'user_no' => 123,	'position_no' => 2000,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 13,	'sequence' => 12,	'team_no' => 9,	'user_no' => 124,	'position_no' => 2000,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 14,	'sequence' => 12,	'team_no' => 9,	'user_no' => 125,	'position_no' => 2000,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 15,	'sequence' => 12,	'team_no' => 9,	'user_no' => 126,	'position_no' => 2000,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 9,	'sequence' => 13,	'team_no' => 9,	'user_no' => 129,	'position_no' => 2000,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 10,	'sequence' => 13,	'team_no' => 9,	'user_no' => 130,	'position_no' => 2000,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 11,	'sequence' => 13,	'team_no' => 9,	'user_no' => 133,	'position_no' => 2000,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 12,	'sequence' => 13,	'team_no' => 9,	'user_no' => 134,	'position_no' => 2000,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 13,	'sequence' => 13,	'team_no' => 9,	'user_no' => 135,	'position_no' => 2000,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 14,	'sequence' => 13,	'team_no' => 9,	'user_no' => 136,	'position_no' => 2000,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 15,	'sequence' => 13,	'team_no' => 9,	'user_no' => 137,	'position_no' => 2000,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 9,	'sequence' => 14,	'team_no' => 10,	'user_no' => 88,	'position_no' => 2002,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 10,	'sequence' => 14,	'team_no' => 10,	'user_no' => 89,	'position_no' => 2002,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 11,	'sequence' => 14,	'team_no' => 10,	'user_no' => 90,	'position_no' => 2002,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 12,	'sequence' => 14,	'team_no' => 10,	'user_no' => 91,	'position_no' => 2002,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 13,	'sequence' => 14,	'team_no' => 10,	'user_no' => 92,	'position_no' => 2002,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 14,	'sequence' => 14,	'team_no' => 10,	'user_no' => 93,	'position_no' => 2002,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 15,	'sequence' => 14,	'team_no' => 10,	'user_no' => 94,	'position_no' => 2002,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 43,	'team_no' => 1,	'user_no' => 199,	'position_no' => 3011,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 44,	'team_no' => 7,	'user_no' => 219,	'position_no' => 3021,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 45,	'team_no' => 7,	'user_no' => 232,	'position_no' => 3031,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 46,	'team_no' => 7,	'user_no' => 233,	'position_no' => 3031,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 47,	'team_no' => 7,	'user_no' => 234,	'position_no' => 3031,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 48,	'team_no' => 7,	'user_no' => 237,	'position_no' => 3031,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 49,	'team_no' => 7,	'user_no' => 238,	'position_no' => 3031,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 50,	'team_no' => 7,	'user_no' => 239,	'position_no' => 3031,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 51,	'team_no' => 2,	'user_no' => 253,	'position_no' => 3081,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 52,	'team_no' => 2,	'user_no' => 254,	'position_no' => 3081,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 53,	'team_no' => 2,	'user_no' => 255,	'position_no' => 3081,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 54,	'team_no' => 2,	'user_no' => 256,	'position_no' => 3081,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 55,	'team_no' => 6,	'user_no' => 298,	'position_no' => 3090,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 56,	'team_no' => 6,	'user_no' => 299,	'position_no' => 3090,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 57,	'team_no' => 4,	'user_no' => 308,	'position_no' => 3040,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 58,	'team_no' => 4,	'user_no' => 309,	'position_no' => 3041,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 59,	'team_no' => 4,	'user_no' => 310,	'position_no' => 3041,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 60,	'team_no' => 4,	'user_no' => 311,	'position_no' => 3041,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 61,	'team_no' => 6,	'user_no' => 323,	'position_no' => 3091,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 62,	'team_no' => 6,	'user_no' => 324,	'position_no' => 3091,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 63,	'team_no' => 7,	'user_no' => 29,	'position_no' => 3021,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 64,	'team_no' => 2,	'user_no' => 32,	'position_no' => 3070,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 65,	'team_no' => 2,	'user_no' => 31,	'position_no' => 3071,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 66,	'team_no' => 8,	'user_no' => 38,	'position_no' => 3050,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 67,	'team_no' => 8,	'user_no' => 39,	'position_no' => 3051,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 68,	'team_no' => 10,	'user_no' => 41,	'position_no' => 3101,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 69,	'team_no' => 1,	'user_no' => 46,	'position_no' => 4000,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 70,	'team_no' => 1,	'user_no' => 15,	'position_no' => 1040,	'created_at' => date("Y-m-d H:i:s")],
          ['drama_no' => 1,	'sequence' => 71,	'team_no' => 1,	'user_no' => 18,	'position_no' => 1040,	'created_at' => date("Y-m-d H:i:s")],

        ];

        DB::table('drama_employees')->insert($employee);
    }
}
