<?php

use Illuminate\Database\Seeder;

class RentalEquipmentTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $equipment = [
          // ['company_name' => '한렌트',	'category_no' => 1,	'equipment_name' => 'RED RAVEN FULL SET',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 1,	'equipment_name' => 'CANON C300 FULL SET',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 1,	'equipment_name' => 'CANON C300MK2 FULL SET',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 1,	'equipment_name' => 'CANON 1DC FULL SET',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 1,	'equipment_name' => 'SONY PXW-FS7 FULL SET',	'equipment_status' => '고장'],
          // ['company_name' => '렌탈샵',	'category_no' => 1,	'equipment_name' => 'CANON C100 FULL SET',	'equipment_status' => '대여 가능'],
          // ['company_name' => '렌탈샵',	'category_no' => 1,	'equipment_name' => 'SONY NEX-FS700 FULL SET',	'equipment_status' => '대여 가능'],
          // ['company_name' => '렌탈샵',	'category_no' => 1,	'equipment_name' => 'SONY A7S II FULL SET',	'equipment_status' => '대여 가능'],
          // ['company_name' => '렌탈샵',	'category_no' => 1,	'equipment_name' => 'CANON 5D MK3 FULL SET',	'equipment_status' => '대여 가능'],
          // ['company_name' => '렌탈샵',	'category_no' => 1,	'equipment_name' => 'NIKON D810+줌렌즈 SET',	'equipment_status' => '대여 가능'],
          // ['company_name' => '렌탈샵',	'category_no' => 1,	'equipment_name' => 'GH4+LUMIX 줌렌즈 SET',	'equipment_status' => '대여중'],
          // ['company_name' => '렌탈샵',	'category_no' => 1,	'equipment_name' => 'TILTA FS7 케이지',	'equipment_status' => '대여 가능'],
          // ['company_name' => '렌탈샵',	'category_no' => 1,	'equipment_name' => 'MOTION7 5Dmark3 ZPDLWL',	'equipment_status' => '대여 가능'],
          // ['company_name' => '렌탈샵',	'category_no' => 2,	'equipment_name' => 'HAN 지미짚',	'equipment_status' => '대여 가능'],
          // ['company_name' => '렌탈샵',	'category_no' => 2,	'equipment_name' => 'MOVEJIB 무브짚',	'equipment_status' => '대여 가능'],
          // ['company_name' => '렌탈샵',	'category_no' => 2,	'equipment_name' => '자바라짚 + 로닌M',	'equipment_status' => '대여 가능'],
          // ['company_name' => '렌탈샵',	'category_no' => 2,	'equipment_name' => 'POLECAM 폴캠',	'equipment_status' => '대여 가능'],
          // ['company_name' => '렌탈샵',	'category_no' => 2,	'equipment_name' => 'KONOVA SUNJIB S700',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 2,	'equipment_name' => 'LIBEC 포타짚 JIB-50HD',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 2,	'equipment_name' => 'LIBEC 포타짚 JB-30HD',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 2,	'equipment_name' => 'LIGHT ARM 라이트암',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 2,	'equipment_name' => '곡선레일 3조',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 2,	'equipment_name' => '삼각대 달리 L',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 2,	'equipment_name' => 'LIBEC 650달리',	'equipment_status' => '고장'],
          // ['company_name' => '한렌트',	'category_no' => 3,	'equipment_name' => 'SONY FDR - AXP55 4K',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 3,	'equipment_name' => 'CANON 5DMARK4',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 3,	'equipment_name' => 'GOPRO5',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 3,	'equipment_name' => 'RED RAVEN',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 3,	'equipment_name' => 'SONY PXW-FS7',	'equipment_status' => '고장'],
          // ['company_name' => '한렌트',	'category_no' => 3,	'equipment_name' => 'SONY PXW-FS7K 렌즈 KIT',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 3,	'equipment_name' => 'SONY PXW-FS5',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 3,	'equipment_name' => 'SONY PXW-FS5K 렌즈 KIT',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 3,	'equipment_name' => 'CANON XC10',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 3,	'equipment_name' => 'SONY A7S II',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 3,	'equipment_name' => 'SONY A7R II',	'equipment_status' => '대여중'],
          // ['company_name' => '렌탈샵',	'category_no' => 3,	'equipment_name' => 'SONY A7S',	'equipment_status' => '대여 가능'],
          // ['company_name' => '렌탈샵',	'category_no' => 3,	'equipment_name' => 'PANASONIC GH4(4K)',	'equipment_status' => '대여 가능'],
          // ['company_name' => '렌탈샵',	'category_no' => 3,	'equipment_name' => 'SONY NEX FS700',	'equipment_status' => '대여 가능'],
          // ['company_name' => '렌탈샵',	'category_no' => 3,	'equipment_name' => 'SONY PMW-200',	'equipment_status' => '대여 가능'],
          // ['company_name' => '렌탈샵',	'category_no' => 3,	'equipment_name' => 'SONY PMW-160',	'equipment_status' => '대여 가능'],
          // ['company_name' => '렌탈샵',	'category_no' => 3,	'equipment_name' => 'SONY PMW-EX3',	'equipment_status' => '대여 가능'],
          // ['company_name' => '렌탈샵',	'category_no' => 3,	'equipment_name' => 'SONY PD170(소품용)',	'equipment_status' => '대여 가능'],
          // ['company_name' => '렌탈샵',	'category_no' => 3,	'equipment_name' => 'PANASONIC DVX100(소품용)',	'equipment_status' => '대여 가능'],
          // ['company_name' => '렌탈샵',	'category_no' => 4,	'equipment_name' => '삼양 XEEN 6SET',	'equipment_status' => '대여중'],
          // ['company_name' => '렌탈샵',	'category_no' => 4,	'equipment_name' => 'ULTRA PRIME',	'equipment_status' => '고장'],
          // ['company_name' => '렌탈샵',	'category_no' => 4,	'equipment_name' => 'CANON CINE Lens 6 SET',	'equipment_status' => '대여 가능'],
          // ['company_name' => '렌탈샵',	'category_no' => 4,	'equipment_name' => 'CANON CINE Lens 5 SET',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 4,	'equipment_name' => 'CARL ZEISS CP.2 SET',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 4,	'equipment_name' => '삼양 XEEN 5SET',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 4,	'equipment_name' => '삼양 XEEN 3SET',	'equipment_status' => '고장'],
          // ['company_name' => '한렌트',	'category_no' => 4,	'equipment_name' => 'CANON K35 SET',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 4,	'equipment_name' => 'CANON 줌렌즈 SET',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 4,	'equipment_name' => 'NIKON 줌렌즈 SET',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 4,	'equipment_name' => 'CANON 단렌즈 SET',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 4,	'equipment_name' => 'SONY 줌렌즈 SET',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 4,	'equipment_name' => 'SONY 단렌즈 SET',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 4,	'equipment_name' => 'PANASONIC 줌렌즈 SET',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 4,	'equipment_name' => '삼양 7EA 단렌즈 SET',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 4,	'equipment_name' => '삼양 6EA 단렌즈 SET',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 4,	'equipment_name' => 'CARL ZEISS ZF 단렌즈 SET',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 4,	'equipment_name' => 'CANON TS-E SET',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 5,	'equipment_name' => 'SACHTLER Video 30',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 5,	'equipment_name' => 'SACHTLER 20P',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 5,	'equipment_name' => 'SACHTLER VIDEO 18S',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 5,	'equipment_name' => 'SACHTLER FSB8',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 5,	'equipment_name' => 'SACHTLER CADDY',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 5,	'equipment_name' => 'SACHTLER PANORAMA',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 5,	'equipment_name' => 'SACHTLER DV8',	'equipment_status' => '대여중'],
          // ['company_name' => '한렌트',	'category_no' => 5,	'equipment_name' => 'SACHTLER DV4',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 5,	'equipment_name' => 'SACHTLER ACE',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 5,	'equipment_name' => 'MANFROTTO 504',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 5,	'equipment_name' => 'MANFROTTO 502',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 5,	'equipment_name' => 'MANFROTTO 500',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 5,	'equipment_name' => 'MANFROTTO 701',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 6,	'equipment_name' => '400D LED 젬볼',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 6,	'equipment_name' => 'LIGHTLIGHTNGRIP HMI 600W 젬볼',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 6,	'equipment_name' => 'JEM BALL 2KW',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 6,	'equipment_name' => 'JEM BALL 1KW',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 6,	'equipment_name' => 'JEM BALL 650W',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 6,	'equipment_name' => 'ARRI HMI D12 1.2KW',	'equipment_status' => '고장'],
          // ['company_name' => '한렌트',	'category_no' => 6,	'equipment_name' => 'ARRI HMI D5 575W',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 6,	'equipment_name' => 'ARRI 2KW',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 6,	'equipment_name' => 'ARRI 1KW',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 6,	'equipment_name' => 'ARRI 650W',	'equipment_status' => '고장'],
          // ['company_name' => '한렌트',	'category_no' => 6,	'equipment_name' => 'ARRI 300W',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 6,	'equipment_name' => 'DEDO SET',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 6,	'equipment_name' => 'FOMEX E600 스튜디오B SET',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 6,	'equipment_name' => 'FOMEX HD1000P SS SET',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 6,	'equipment_name' => 'FILLEX 3LIGHT KIT',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 6,	'equipment_name' => 'KINO 4FT 4BANK',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 6,	'equipment_name' => 'KINO 2FT 4BANK',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 6,	'equipment_name' => 'LEDKINO 2FT 4BANK',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 6,	'equipment_name' => 'LEDGO LG-1200',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 6,	'equipment_name' => 'LEDGO LG-1200 MCSII',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 6,	'equipment_name' => 'LEDGO LG-900',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 6,	'equipment_name' => 'MEGALED FL-120B',	'equipment_status' => '대여 가능'],
          // ['company_name' => 'LEDRENT',	'category_no' => 6,	'equipment_name' => 'MINI LED',	'equipment_status' => '대여 가능'],
          // ['company_name' => 'LEDRENT',	'category_no' => 7,	'equipment_name' => 'SONY UWP-D11',	'equipment_status' => '대여 가능'],
          // ['company_name' => 'LEDRENT',	'category_no' => 7,	'equipment_name' => 'SENNHEISER 416P',	'equipment_status' => '대여 가능'],
          // ['company_name' => 'LEDRENT',	'category_no' => 7,	'equipment_name' => 'SENNHEISER ME66',	'equipment_status' => '대여중'],
          // ['company_name' => 'LEDRENT',	'category_no' => 7,	'equipment_name' => 'RODE NTG-3',	'equipment_status' => '대여 가능'],
          // ['company_name' => 'LEDRENT',	'category_no' => 7,	'equipment_name' => 'RODE VM PRO',	'equipment_status' => '대여 가능'],
          // ['company_name' => 'LEDRENT',	'category_no' => 7,	'equipment_name' => 'RODE SVM PRO',	'equipment_status' => '대여 가능'],
          // ['company_name' => 'LEDRENT',	'category_no' => 7,	'equipment_name' => 'RODE SVM PRO',	'equipment_status' => '대여 가능'],
          // ['company_name' => 'LEDRENT',	'category_no' => 7,	'equipment_name' => 'TASCAM TM-2X',	'equipment_status' => '대여 가능'],
          // ['company_name' => 'LEDRENT',	'category_no' => 7,	'equipment_name' => 'SENNHEISER 무선 핀마이크',	'equipment_status' => '대여 가능'],
          // ['company_name' => 'LEDRENT',	'category_no' => 7,	'equipment_name' => 'SONY UWP-V1',	'equipment_status' => '대여 가능'],
          // ['company_name' => 'LEDRENT',	'category_no' => 7,	'equipment_name' => 'TASCAM DR100MK4',	'equipment_status' => '대여 가능'],
          // ['company_name' => 'LEDRENT',	'category_no' => 7,	'equipment_name' => 'TASCAM HD-P2',	'equipment_status' => '고장'],
          // ['company_name' => '한렌트',	'category_no' => 7,	'equipment_name' => 'TASCAM DR-680',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 7,	'equipment_name' => 'TASCAM DR-44WL',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 7,	'equipment_name' => 'SONY PCM-D50',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 8,	'equipment_name' => 'TVLOGIC 17',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 8,	'equipment_name' => 'TVLOGIC 24',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 8,	'equipment_name' => 'TVLOGIC 17-176A',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 8,	'equipment_name' => 'TVLOGIC 7',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 8,	'equipment_name' => 'TVLOGIC 7-071W',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 8,	'equipment_name' => 'BON 7',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 8,	'equipment_name' => 'BON 5',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 8,	'equipment_name' => 'TVLOGIC 5.6',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 8,	'equipment_name' => 'TVLOGIC 5.6-058W',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 8,	'equipment_name' => 'AJA CONVERTER',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 8,	'equipment_name' => 'BM HDMI TO SDI CONVERTER',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 8,	'equipment_name' => 'ATOMOS H2S 컨버터',	'equipment_status' => '고장'],
          // ['company_name' => '한렌트',	'category_no' => 9,	'equipment_name' => 'APPLE MACBOOK RETINA 15',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 9,	'equipment_name' => 'APPLE MACBOOK PRO 17',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 9,	'equipment_name' => 'APPLE MACBOOK PRO 15',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 9,	'equipment_name' => 'SAMSUNG NOTEBOOK 15',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 9,	'equipment_name' => 'SAMSUNG NOTEBOOK 17',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 9,	'equipment_name' => '외장하드 2T',	'equipment_status' => '고장'],
          // ['company_name' => '한렌트',	'category_no' => 9,	'equipment_name' => '외장하드 1T',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 9,	'equipment_name' => 'Digibeta tape 6분',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 9,	'equipment_name' => 'Digibeta tape 32분',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 9,	'equipment_name' => 'Digibeta tape 64분',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 9,	'equipment_name' => 'Digibeta tape 96분',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 9,	'equipment_name' => 'Digibeta tape 128분',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 9,	'equipment_name' => 'Digibeta tape 160분',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 10,	'equipment_name' => 'AMIS 무전기 A-1 5SET',	'equipment_status' => '대여중'],
          // ['company_name' => '한렌트',	'category_no' => 10,	'equipment_name' => 'SANDISK CF MEMORY 64G',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 10,	'equipment_name' => 'SONY SXS MEMORY 8G',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 10,	'equipment_name' => 'SONY SXS MEMORY 16G',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 10,	'equipment_name' => 'SONY SXS MEMORY 64G',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 10,	'equipment_name' => '세로그립',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 10,	'equipment_name' => '링 CPL /ND 필터',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 10,	'equipment_name' => 'HONDA 6.5KW 발전기',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 10,	'equipment_name' => 'HONDA 3KW 발전기',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 10,	'equipment_name' => '헤이저 포그 머신',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 10,	'equipment_name' => '포그머신',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 10,	'equipment_name' => '강풍기',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 10,	'equipment_name' => '촬영 카트',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 10,	'equipment_name' => '촬영용 테이블',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 10,	'equipment_name' => 'KOVEA 하이백 체어',	'equipment_status' => '대여중'],
          // ['company_name' => '한렌트',	'category_no' => 10,	'equipment_name' => 'KOVEA 2WAY CHAIR',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 10,	'equipment_name' => 'KOVEA RELAX CHAIR',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 10,	'equipment_name' => 'KOVEA MASTER CHAIR1',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 10,	'equipment_name' => 'KOVEA MASTER CHAIR2',	'equipment_status' => '대여 가능'],
          // ['company_name' => '한렌트',	'category_no' => 10,	'equipment_name' => 'KOVEA MASTER CHAIR3',	'equipment_status' => '대여 가능'],

          ['company_name' => 'HAN RENT',	'category_no' => 1,	'equipment_name' => 'RED RAVEN FULL SET',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 1,	'equipment_name' => 'CANON C300 FULL SET',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 1,	'equipment_name' => 'CANON C300MK2 FULL SET',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 1,	'equipment_name' => 'CANON 1DC FULL SET',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 1,	'equipment_name' => 'SONY PXW-FS7 FULL SET',	'equipment_status' => '故障'],
          ['company_name' => 'RENTAL SHOP',	'category_no' => 1,	'equipment_name' => 'CANON C100 FULL SET',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'RENTAL SHOP',	'category_no' => 1,	'equipment_name' => 'SONY NEX-FS700 FULL SET',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'RENTAL SHOP',	'category_no' => 1,	'equipment_name' => 'SONY A7S II FULL SET',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'RENTAL SHOP',	'category_no' => 1,	'equipment_name' => 'CANON 5D MK3 FULL SET',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'RENTAL SHOP',	'category_no' => 1,	'equipment_name' => 'NIKON D810+ズームレンズ SET',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'RENTAL SHOP',	'category_no' => 1,	'equipment_name' => 'GH4+LUMIX ズームレンズ SET',	'equipment_status' => '貸与中'],
          ['company_name' => 'RENTAL SHOP',	'category_no' => 1,	'equipment_name' => 'TILTA FS7 ',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'RENTAL SHOP',	'category_no' => 1,	'equipment_name' => 'MOTION7 5Dmark3 ZPDLWL',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'RENTAL SHOP',	'category_no' => 2,	'equipment_name' => 'HAN ジミジプ',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'RENTAL SHOP',	'category_no' => 2,	'equipment_name' => 'MOVEJIB',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'RENTAL SHOP',	'category_no' => 2,	'equipment_name' => 'ジミジプ + M',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'RENTAL SHOP',	'category_no' => 2,	'equipment_name' => 'POLECAM ',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'RENTAL SHOP',	'category_no' => 2,	'equipment_name' => 'KONOVA SUNJIB S700',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 2,	'equipment_name' => 'LIBEC  JIB-50HD',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 2,	'equipment_name' => 'LIBEC  JB-30HD',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 2,	'equipment_name' => 'LIGHT ARM',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 2,	'equipment_name' => '曲線のレール',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 2,	'equipment_name' => '三脚 L',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 2,	'equipment_name' => 'LIBEC 650',	'equipment_status' => '故障'],
          ['company_name' => 'HAN RENT',	'category_no' => 3,	'equipment_name' => 'SONY FDR - AXP55 4K',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 3,	'equipment_name' => 'CANON 5DMARK4',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 3,	'equipment_name' => 'GOPRO5',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 3,	'equipment_name' => 'RED RAVEN',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 3,	'equipment_name' => 'SONY PXW-FS7',	'equipment_status' => '故障'],
          ['company_name' => 'HAN RENT',	'category_no' => 3,	'equipment_name' => 'SONY PXW-FS7K レンズ KIT',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 3,	'equipment_name' => 'SONY PXW-FS5',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 3,	'equipment_name' => 'SONY PXW-FS5K レンズ KIT',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 3,	'equipment_name' => 'CANON XC10',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 3,	'equipment_name' => 'SONY A7S II',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 3,	'equipment_name' => 'SONY A7R II',	'equipment_status' => '貸与中'],
          ['company_name' => 'RENTAL SHOP',	'category_no' => 3,	'equipment_name' => 'SONY A7S',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'RENTAL SHOP',	'category_no' => 3,	'equipment_name' => 'PANASONIC GH4(4K)',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'RENTAL SHOP',	'category_no' => 3,	'equipment_name' => 'SONY NEX FS700',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'RENTAL SHOP',	'category_no' => 3,	'equipment_name' => 'SONY PMW-200',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'RENTAL SHOP',	'category_no' => 3,	'equipment_name' => 'SONY PMW-160',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'RENTAL SHOP',	'category_no' => 3,	'equipment_name' => 'SONY PMW-EX3',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'RENTAL SHOP',	'category_no' => 3,	'equipment_name' => 'SONY PD170',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'RENTAL SHOP',	'category_no' => 3,	'equipment_name' => 'PANASONIC DVX100',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'RENTAL SHOP',	'category_no' => 4,	'equipment_name' => 'XEEN 6SET',	'equipment_status' => '貸与中'],
          ['company_name' => 'RENTAL SHOP',	'category_no' => 4,	'equipment_name' => 'ULTRA PRIME',	'equipment_status' => '故障'],
          ['company_name' => 'RENTAL SHOP',	'category_no' => 4,	'equipment_name' => 'CANON CINE Lens 6 SET',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'RENTAL SHOP',	'category_no' => 4,	'equipment_name' => 'CANON CINE Lens 5 SET',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 4,	'equipment_name' => 'CARL ZEISS CP.2 SET',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 4,	'equipment_name' => 'XEEN 5SET',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 4,	'equipment_name' => 'XEEN 3SET',	'equipment_status' => '故障'],
          ['company_name' => 'HAN RENT',	'category_no' => 4,	'equipment_name' => 'CANON K35 SET',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 4,	'equipment_name' => 'CANON ズームレンズ SET',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 4,	'equipment_name' => 'NIKON ズームレンズ SET',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 4,	'equipment_name' => 'CANON レンズ SET',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 4,	'equipment_name' => 'SONY ズームレンズ SET',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 4,	'equipment_name' => 'SONY レンズ SET',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 4,	'equipment_name' => 'PANASONIC ズームレンズ SET',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 4,	'equipment_name' => '7EA レンズ SET',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 4,	'equipment_name' => '6EA レンズ SET',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 4,	'equipment_name' => 'CARL ZEISS ZF レンズ SET',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 4,	'equipment_name' => 'CANON TS-E SET',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 5,	'equipment_name' => 'SACHTLER Video 30',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 5,	'equipment_name' => 'SACHTLER 20P',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 5,	'equipment_name' => 'SACHTLER VIDEO 18S',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 5,	'equipment_name' => 'SACHTLER FSB8',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 5,	'equipment_name' => 'SACHTLER CADDY',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 5,	'equipment_name' => 'SACHTLER PANORAMA',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 5,	'equipment_name' => 'SACHTLER DV8',	'equipment_status' => '貸与中'],
          ['company_name' => 'HAN RENT',	'category_no' => 5,	'equipment_name' => 'SACHTLER DV4',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 5,	'equipment_name' => 'SACHTLER ACE',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 5,	'equipment_name' => 'MANFROTTO 504',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 5,	'equipment_name' => 'MANFROTTO 502',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 5,	'equipment_name' => 'MANFROTTO 500',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 5,	'equipment_name' => 'MANFROTTO 701',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 6,	'equipment_name' => '400D LED zemball',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 6,	'equipment_name' => 'LIGHTLIGHTNGRIP HMI 600W zemball',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 6,	'equipment_name' => 'JEM BALL 2KW',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 6,	'equipment_name' => 'JEM BALL 1KW',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 6,	'equipment_name' => 'JEM BALL 650W',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 6,	'equipment_name' => 'ARRI HMI D12 1.2KW',	'equipment_status' => '故障'],
          ['company_name' => 'HAN RENT',	'category_no' => 6,	'equipment_name' => 'ARRI HMI D5 575W',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 6,	'equipment_name' => 'ARRI 2KW',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 6,	'equipment_name' => 'ARRI 1KW',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 6,	'equipment_name' => 'ARRI 650W',	'equipment_status' => '故障'],
          ['company_name' => 'HAN RENT',	'category_no' => 6,	'equipment_name' => 'ARRI 300W',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 6,	'equipment_name' => 'DEDO SET',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 6,	'equipment_name' => 'FOMEX E600 studioB SET',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 6,	'equipment_name' => 'FOMEX HD1000P SS SET',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 6,	'equipment_name' => 'FILLEX 3LIGHT KIT',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 6,	'equipment_name' => 'KINO 4FT 4BANK',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 6,	'equipment_name' => 'KINO 2FT 4BANK',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 6,	'equipment_name' => 'LEDKINO 2FT 4BANK',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 6,	'equipment_name' => 'LEDGO LG-1200',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 6,	'equipment_name' => 'LEDGO LG-1200 MCSII',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 6,	'equipment_name' => 'LEDGO LG-900',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 6,	'equipment_name' => 'MEGALED FL-120B',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'LEDRENT',	'category_no' => 6,	'equipment_name' => 'MINI LED',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'LEDRENT',	'category_no' => 7,	'equipment_name' => 'SONY UWP-D11',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'LEDRENT',	'category_no' => 7,	'equipment_name' => 'SENNHEISER 416P',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'LEDRENT',	'category_no' => 7,	'equipment_name' => 'SENNHEISER ME66',	'equipment_status' => '貸与中'],
          ['company_name' => 'LEDRENT',	'category_no' => 7,	'equipment_name' => 'RODE NTG-3',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'LEDRENT',	'category_no' => 7,	'equipment_name' => 'RODE VM PRO',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'LEDRENT',	'category_no' => 7,	'equipment_name' => 'RODE SVM PRO',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'LEDRENT',	'category_no' => 7,	'equipment_name' => 'RODE SVM PRO',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'LEDRENT',	'category_no' => 7,	'equipment_name' => 'TASCAM TM-2X',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'LEDRENT',	'category_no' => 7,	'equipment_name' => 'SENNHEISER pin mike',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'LEDRENT',	'category_no' => 7,	'equipment_name' => 'SONY UWP-V1',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'LEDRENT',	'category_no' => 7,	'equipment_name' => 'TASCAM DR100MK4',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'LEDRENT',	'category_no' => 7,	'equipment_name' => 'TASCAM HD-P2',	'equipment_status' => '故障'],
          ['company_name' => 'HAN RENT',	'category_no' => 7,	'equipment_name' => 'TASCAM DR-680',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 7,	'equipment_name' => 'TASCAM DR-44WL',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 7,	'equipment_name' => 'SONY PCM-D50',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 8,	'equipment_name' => 'TVLOGIC 17',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 8,	'equipment_name' => 'TVLOGIC 24',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 8,	'equipment_name' => 'TVLOGIC 17-176A',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 8,	'equipment_name' => 'TVLOGIC 7',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 8,	'equipment_name' => 'TVLOGIC 7-071W',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 8,	'equipment_name' => 'BON 7',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 8,	'equipment_name' => 'BON 5',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 8,	'equipment_name' => 'TVLOGIC 5.6',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 8,	'equipment_name' => 'TVLOGIC 5.6-058W',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 8,	'equipment_name' => 'AJA CONVERTER',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 8,	'equipment_name' => 'BM HDMI TO SDI CONVERTER',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 8,	'equipment_name' => 'ATOMOS H2S CONVERTER',	'equipment_status' => '故障'],
          ['company_name' => 'HAN RENT',	'category_no' => 9,	'equipment_name' => 'APPLE MACBOOK RETINA 15',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 9,	'equipment_name' => 'APPLE MACBOOK PRO 17',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 9,	'equipment_name' => 'APPLE MACBOOK PRO 15',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 9,	'equipment_name' => 'SAMSUNG NOTEBOOK 15',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 9,	'equipment_name' => 'SAMSUNG NOTEBOOK 17',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 9,	'equipment_name' => '外付のハードディスク 2T',	'equipment_status' => '故障'],
          ['company_name' => 'HAN RENT',	'category_no' => 9,	'equipment_name' => '外付のハードディスク 1T',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 9,	'equipment_name' => 'Digibeta tape 6分',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 9,	'equipment_name' => 'Digibeta tape 32分',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 9,	'equipment_name' => 'Digibeta tape 64分',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 9,	'equipment_name' => 'Digibeta tape 96分',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 9,	'equipment_name' => 'Digibeta tape 128分',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 9,	'equipment_name' => 'Digibeta tape 160分',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 10,	'equipment_name' => 'AMIS A-1 5SET',	'equipment_status' => '貸与中'],
          ['company_name' => 'HAN RENT',	'category_no' => 10,	'equipment_name' => 'SANDISK CF MEMORY 64G',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 10,	'equipment_name' => 'SONY SXS MEMORY 8G',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 10,	'equipment_name' => 'SONY SXS MEMORY 16G',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 10,	'equipment_name' => 'SONY SXS MEMORY 64G',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 10,	'equipment_name' => '縦グリップ',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 10,	'equipment_name' => 'RING CPL /ND FILTER',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 10,	'equipment_name' => 'HONDA 6.5KW 発電機',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 10,	'equipment_name' => 'HONDA 3KW 発電機',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 10,	'equipment_name' => 'ヘイジョ・フォッグマシン',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 10,	'equipment_name' => 'フォッグマシン',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 10,	'equipment_name' => '強風機',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 10,	'equipment_name' => '撮影カート',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 10,	'equipment_name' => '撮影 テーブル',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 10,	'equipment_name' => 'KOVEA CHAIR',	'equipment_status' => '貸与中'],
          ['company_name' => 'HAN RENT',	'category_no' => 10,	'equipment_name' => 'KOVEA 2WAY CHAIR',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 10,	'equipment_name' => 'KOVEA RELAX CHAIR',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 10,	'equipment_name' => 'KOVEA MASTER CHAIR1',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 10,	'equipment_name' => 'KOVEA MASTER CHAIR2',	'equipment_status' => '貸与 可能'],
          ['company_name' => 'HAN RENT',	'category_no' => 10,	'equipment_name' => 'KOVEA MASTER CHAIR3',	'equipment_status' => '貸与 可能'],


        ];

        DB::table('rental_equipments')->insert($equipment);
    }
}
