<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        // DB::table('users')->insert(
        //   ['user_type' => '배우','id' => 'aid1''password' => bcrypt(123456),'name' => '조인성','birth' => 19810728,'email' => 'insung@gmail.com','tel' => '01078977987','type' => '배우','introduce' => '인성을 보여드리겠습니다.','stage_name' => '조인성','gender' => 'm','height' => 186,'weight' => 76,'local' => '서울특별시','career' => '디어 마이 프렌즈',]
        // );


        $users = [

          // ['user_type'=>'개인',	'id' => 'aid1',	'password' => bcrypt(123456),	'name' => '조인성',	'birth' => 19810728,	'email' => 'insung@gmail.com',	'tel' => '010-7897-7987',	'type' => '배우',	'introduce' => '인성을 보여드리겠습니다.',	'stage_name' => '조인성',
          // 'gender' => 'm',	'height' => 186,	'weight' => 76,	'local' => '서울특별시',	'career' => '디어 마이 프렌즈'],
          // ['user_type'=>'개인',	'id' => 'aid2',	'password' => bcrypt(123456),	'name' => '김도진',	'birth' => 19771110,	'email' => '1bin@naver.com',	'tel' => '010-1111-1111',	'type' => '배우',	'introduce' => '말이 필요하나요',	'stage_name' => '원빈',
          // 'gender' => 'm',	'height' => 178,	'weight' => 65,	'local' => '강원도 강릉',	'career' => '아저씨'],
          // ['user_type'=>'개인',	'id' => 'aid3',	'password' => bcrypt(123456),	'name' => '유해진',	'birth' => 19700104,	'email' => 'yousun@gmail.com',	'tel' => '010-1231-1231',	'type' => '배우',	'introduce' => '제가 바로 유해진',	'stage_name' => '유해진',
          // 'gender' => 'm',	'height' => 174,	'weight' => 65,	'local' => '충청북도 청주',	'career' => '럭키'],
          // ['user_type'=>'개인',	'id' => 'aid4',	'password' => bcrypt(123456),	'name' => '김태희',	'birth' => 19800329,	'email' => 'taehee@naver.com',	'tel' => '010-1233-1233',	'type' => '배우',	'introduce' => '미녀배우 김태희입니다.',	'stage_name' => '김태희',
          // 'gender' => 'w',	'height' => 162,	'weight' => 45,	'local' => '울산광역시',	'career' => '용팔이'],
          // ['user_type'=>'개인',	'id' => 'aid5',	'password' => bcrypt(123456),	'name' => '김태리',	'birth' => 19900424,	'email' => 'lee@gmail.com',	'tel' => '010-1212-1212',	'type' => '배우',	'introduce' => '김태리입니다.',	'stage_name' => '김태리',
          // 'gender' => 'w',	'height' => 166,	'weight' => 48,	'local' => '인천광역시',	'career' => '아가씨'],
          // ['user_type'=>'개인',	'id' => 'sid1',	'password' => bcrypt(123456),	'name' => '박찬욱',	'birth' => 19630823,	'email' => 'chan@gmail.com',	'tel' => '010-5555-5555',	'type' => '촬영',	'introduce' => '제2의 아가씨 제가만들겠습니다.',	'stage_name' => '박찬욱',
          // 'gender' => 'm',	'height' => 175,	'weight' => 70,	'local' => '경기도 광주',	'career' => '아가씨'],
          // ['user_type'=>'개인',	'id' => 'sid2',	'password' => bcrypt(123456),	'name' => '장태유',	'birth' => 19720505,	'email' => 'starkarakita@naver.com',	'tel' => '010-5556-5556',	'type' => '촬영',	'introduce' => '별에서온 그대',	'stage_name' => '장태유',
          // 'gender' => 'm',	'height' => 175,	'weight' => 70,	'local' => '경상남도 진주',	'career' => '별에서온그대'],
          // ['user_type'=>'개인',	'id' => 'sid3',	'password' => bcrypt(123456),	'name' => '김조감',	'birth' => 19770407,	'email' => 'jogam@naver.com',	'tel' => '010-3333-3333',	'type' => '조명',	'introduce' => '조명감독이에용',	'stage_name' => '김조감',
          // 'gender' => 'm',	'height' => 178,	'weight' => 85,	'local' => '서울특별시',	'career' => '별에서온그대'],
          // ['user_type'=>'개인',	'id' => 'sid4',	'password' => bcrypt(123456),	'name' => '이조명',	'birth' => 19900505,	'email' => 'jmlee@gmail.com',	'tel' => '010-3334-3334',	'type' => '조명',	'introduce' => '조명 잘할 수 있어요',	'stage_name' => '이조명',
          // 'gender' => 'm',	'height' => 191,	'weight' => 86,	'local' => '서울특별시',	'career' => '취업은 영진'],
          // ['user_type'=>'개인',	'id' => 'sid5',	'password' => bcrypt(123456),	'name' => '백관리',	'birth' => 19850806,	'email' => 'sch@naver.com',	'tel' => '010-1230-3651',	'type' => '스케줄',	'introduce' => '관리 잘해요',	'stage_name' => '백관리',
          // 'gender' => 'w',	'height' => 162,	'weight' => 45,	'local' => '서울특별시',	'career' => '취업은 영진'],
          // ['user_type'=>'개인',	'id' => 'sid6',	'password' => bcrypt(123456),	'name' => '은관리',	'birth' => 19830507,	'email' => 'sch2@naver.com',	'tel' => '010-3651-1230',	'type' => '스케줄',	'introduce' => '스케줄 관리 하면 저입니다.',	'stage_name' => '은관리',
          // 'gender' => 'm',	'height' => 170,	'weight' => 75,	'local' => '경기도 수원',	'career' => '용팔이'],
          // ['user_type'=>'개인',	'id' => 'sid7',	'password' => bcrypt(123456),	'name' => '김조명',	'birth' => 19810501,	'email' => 'jmkim@naver.com',	'tel' => '010-1911-1911',	'type' => '조명',	'introduce' => '조명 3년차에요',	'stage_name' => '김조명',
          // 'gender' => 'm',	'height' => 169,	'weight' => 65,	'local' => '서울특별시',	'career' => '도깨비'],
          // ['user_type'=>'개인',	'id' => 'sid8',	'password' => bcrypt(123456),	'name' => '장조명',	'birth' => 19811212,	'email' => 'jmjang@gmail.com',	'tel' => '010-5885-5885',	'type' => '조명',	'introduce' => '조명 1년차지만 열심히하겠습니다.',	'stage_name' => '장조명',
          // 'gender' => 'm',	'height' => 172,	'weight' => 70,	'local' => '경기도 부천',	'career' => '도깨비'],
          // ['user_type'=>'개인',	'id' => 'sid9',	'password' => bcrypt(123456),	'name' => '조녹음',	'birth' => 19881216,	'email' => 'jorec@naver.com',	'tel' => '010-1666-6661',	'type' => '녹음',	'introduce' => '녹음 2년차',	'stage_name' => '조녹음',
          // 'gender' => 'm',	'height' => 189,	'weight' => 75,	'local' => '서울특별시',	'career' => '지금'],
          // ['user_type'=>'개인',	'id' => 'sid10',	'password' => bcrypt(123456),	'name' => '지작가',	'birth' => 19800501,	'email' => 'jijakka@naver.com',	'tel' => '010-2236-2246',	'type' => '작가',	'introduce' => '시나리오잘써요',	'stage_name' => '지작가',
          // 'gender' => 'm',	'height' => 180,	'weight' => 73,	'local' => '서울특별시',	'career' => '새벽'],
          // ['user_type'=>'개인',	'id' => 'sid11',	'password' => bcrypt(123456),	'name' => '이작가',	'birth' => 19780603,	'email' => 'jklee@naver.com',	'tel' => '010-2224-2256',	'type' => '작가',	'introduce' => '시나리오 너무 잘씁니다.',	'stage_name' => '이작가',
          // 'gender' => 'w',	'height' => 169,	'weight' => 50,	'local' => '서울특별시',	'career' => '용팔이'],
          // ['user_type'=>'개인',	'id' => 'sid12',	'password' => bcrypt(123456),	'name' => '김작가',	'birth' => 19770808,	'email' => 'jkkim@naver.com',	'tel' => '010-2223-2223',	'type' => '작가',	'introduce' => '시나리오 굉장히 잘씁니다.',	'stage_name' => '김작가',
          // 'gender' => 'm',	'height' => 177,	'weight' => 70,	'local' => '서울특별시',	'career' => '취업은 영진'],
          // ['user_type'=>'개인',	'id' => 'sid13',	'password' => bcrypt(123456),	'name' => '조작가',	'birth' => 19880906,	'email' => 'jojakka@gmail.com',	'tel' => '010-2222-2222',	'type' => '작가',	'introduce' => '작품하나는 기가 막힙니다.',	'stage_name' => '조작가',
          // 'gender' => 'w',	'height' => 155,	'weight' => 44,	'local' => '서울특별시',	'career' => '야경꾼 일지'],
          // ['user_type'=>'개인',	'id' => 'sid14',	'password' => bcrypt(123456),	'name' => '감녹음',	'birth' => 19750530,	'email' => 'nokkam@naver.com',	'tel' => '010-5555-5522',	'type' => '녹음',	'introduce' => '녹음 감독입니다.',	'stage_name' => '감녹음',
          // 'gender' => 'm',	'height' => 169,	'weight' => 70,	'local' => '서울특별시',	'career' => '태양의 후예'],
          // ['user_type'=>'개인',	'id' => 'sid15',	'password' => bcrypt(123456),	'name' => '김소품',	'birth' => 19900108,	'email' => 'sopum@naver.com',	'tel' => '010-1133-1945',	'type' => '녹음',	'introduce' => '잘할 자신 있어요',	'stage_name' => '김소품',
          // 'gender' => 'w',	'height' => 158,	'weight' => 53,	'local' => '경기도 과천',	'career' => '미생'],
          // ['user_type'=>'개인',	'id' => 'sid16',	'password' => bcrypt(123456),	'name' => '김미감',	'birth' => 19781001,	'email' => 'misulkam1@gmail.com',	'tel' => '010-5566-5598',	'type' => '미술',	'introduce' => '미술 경력 10년차',	'stage_name' => '김미감',
          // 'gender' => 'w',	'height' => 155,	'weight' => 52,	'local' => '서울특별시',	'career' => '응답하라1997'],
          // ['user_type'=>'개인',	'id' => 'sid17',	'password' => bcrypt(123456),	'name' => '김미술',	'birth' => 19900506,	'email' => 'misul324@naver.com',	'tel' => '010-1218-1218',	'type' => '미술',	'introduce' => '미술 경력 3년차',	'stage_name' => '김미술',
          // 'gender' => 'm',	'height' => 166,	'weight' => 55,	'local' => '경기도 파주',	'career' => '용팔이'],
          // ['user_type'=>'개인',	'id' => 'sid18',	'password' => bcrypt(123456),	'name' => '무감술',	'birth' => 19821111,	'email' => 'mukam@naver.com',	'tel' => '010-5959-5959',	'type' => '무술',	'introduce' => '액션의 진수',	'stage_name' => '무감술',
          // 'gender' => 'm',	'height' => 199,	'weight' => 75,	'local' => '제주특별자치도',	'career' => '태양의 후예'],
          // ['user_type'=>'개인',	'id' => 'sid19',	'password' => bcrypt(123456),	'name' => '김연출',	'birth' => 19880105,	'email' => 'chulchul@naver.com',	'tel' => '010-1155-5511',	'type' => '연출',	'introduce' => '맡겨만 주세요',	'stage_name' => '김연출',
          // 'gender' => 'm',	'height' => 186,	'weight' => 77,	'local' => '서울서울특별시',	'career' => '싸우자귀신아'],
          // ['user_type'=>'개인',	'id' => 'sid20',	'password' => bcrypt(123456),	'name' => '이연출',	'birth' => 19970630,	'email' => 'yearlee@gmail.com',	'tel' => '010-1122-2211',	'type' => '연출',	'introduce' => '연출',	'stage_name' => '이연출',
          // 'gender' => 'm',	'height' => 177,	'weight' => 76,	'local' => '서울서울특별시',	'career' => '화랑'],
          // ['user_type'=>'개인',	'id' => 'sid21',	'password' => bcrypt(123456),	'name' => '김잡스',	'birth' => 19950405,	'email' => 'jobs@naver.com',	'tel' => '010-1444-4422',	'type' => '연출',	'introduce' => '뭐든지 잘합니다.',	'stage_name' => '김잡스',
          // 'gender' => 'm',	'height' => 175,	'weight' => 74,	'local' => '경기도 파주',	'career' => '피노키오'],
          // ['user_type'=>'개인',	'id' => 'sid22',	'password' => bcrypt(123456),	'name' => '노홍돌',	'birth' => 19920303,	'email' => 'fd23@gmail.com',	'tel' => '010-1239-9988',	'type' => '연출',	'introduce' => '정말 잘할 수 있어요',	'stage_name' => '노홍돌',
          // 'gender' => 'm',	'height' => 176,	'weight' => 73,	'local' => '서울특별시',	'career' => '시크릿가든'],
          // ['user_type'=>'개인',	'id' => 'sid23',	'password' => bcrypt(123456),	'name' => '손편수',	'birth' => 19850825,	'email' => 'houhome@gmail.com',	'tel' => '010-1222-7845',	'type' => '편집',	'introduce' => '음악도 가능해요',	'stage_name' => '손편수',
          // 'gender' => 'm',	'height' => 168,	'weight' => 71,	'local' => '경기도 연천',	'career' => '베이비시터'],
          // ['user_type'=>'개인',	'id' => 'sid24',	'password' => bcrypt(123456),	'name' => '김현태',	'birth' => 19900206,	'email' => 'kamera@gmail.com',	'tel' => '010-1335-3322',	'type' => '촬영',	'introduce' => '편집까지 오케이',	'stage_name' => '김현태',
          // 'gender' => 'm',	'height' => 169,	'weight' => 72,	'local' => '서울특별시',	'career' => '프린스의왕자'],
          // ['user_type'=>'개인',	'id' => 'sid25',	'password' => bcrypt(123456),	'name' => '소지손',	'birth' => 19900224,	'email' => 'camera@naver.com',	'tel' => '010-1111-3333',	'type' => '촬영',	'introduce' => '잘부탁드립니다.',	'stage_name' => '소지손',
          // 'gender' => 'm',	'height' => 175,	'weight' => 73,	'local' => '인천광역시',	'career' => '유령'],
          // ['user_type'=>'개인',	'id' => 'sid26',	'password' => bcrypt(123456),	'name' => 'andy',	'birth' => 19870723,	'email' => 'music@naver.com',	'tel' => '010-1811-1814',	'type' => '음악',	'introduce' => '뮤비경험다수',	'stage_name' => 'andy',
          // 'gender' => 'm',	'height' => 167,	'weight' => 69,	'local' => '인천광역시',	'career' => '너의목소리가들려'],
          // ['user_type'=>'개인',	'id' => 'sid27',	'password' => bcrypt(123456),	'name' => '이중호',	'birth' => 19780913,	'email' => 'sound@naver.com',	'tel' => '010-1319-1919',	'type' => '음악',	'introduce' => '해외유학파',	'stage_name' => '이중호',
          // 'gender' => 'm',	'height' => 179,	'weight' => 68,	'local' => '인천광역시',	'career' => '빅'],
          // ['user_type'=>'개인',	'id' => 'sid28',	'password' => bcrypt(123456),	'name' => '장소신',	'birth' => 19770727,	'email' => 'location@gmail.com',	'tel' => '010-2424-2424',	'type' => '로케이션매니저',	'introduce' => '장소는 내게',	'stage_name' => '장소신',
          // 'gender' => 'm',	'height' => 172,	'weight' => 60,	'local' => '서울특별시',	'career' => '별에서온그대'],
          // ['user_type'=>'개인',	'id' => 'sid29',	'password' => bcrypt(123456),	'name' => '구이현',	'birth' => 19830323,	'email' => 'hairkoo@gmail.com',	'tel' => '010-5656-5655',	'type' => '헤어',	'introduce' => '잘합니다.',	'stage_name' => '구이현',
          // 'gender' => 'w',	'height' => 168,	'weight' => 53,	'local' => '경기도 부천',	'career' => '빅'],
          // ['user_type'=>'개인',	'id' => 'sid30',	'password' => bcrypt(123456),	'name' => '손혜진',	'birth' => 19910801,	'email' => 'hairhair@naver.com',	'tel' => '010-5955-5544',	'type' => '헤어',	'introduce' => '무슨 헤어든 가능',	'stage_name' => '손혜진',
          // 'gender' => 'w',	'height' => 162,	'weight' => 50,	'local' => '경기도 수원',	'career' => '드림하이'],
          // ['user_type'=>'개인',	'id' => 'sid31',	'password' => bcrypt(123456),	'name' => '기사현',	'birth' => 19690830,	'email' => 'busya@gmail.com',	'tel' => '010-2111-2525',	'type' => '운송',	'introduce' => '버스 순식간입니다',	'stage_name' => '기사현',
          // 'gender' => 'm',	'height' => 170,	'weight' => 77,	'local' => '경기도 화성',	'career' => '나인'],
          // ['user_type'=>'개인',	'id' => 'sid32',	'password' => bcrypt(123456),	'name' => '조수신',	'birth' => 19650410,	'email' => 'fastjo@gmail.com',	'tel' => '010-2525-2424',	'type' => '운송',	'introduce' => '안전이 제일',	'stage_name' => '조수신',
          // 'gender' => 'm',	'height' => 169,	'weight' => 70,	'local' => '경기도 수원',	'career' => '꽃보다남자'],
          // ['user_type'=>'개인',	'id' => 'sid33',	'password' => bcrypt(123456),	'name' => '김선붕',	'birth' => 19890621,	'email' => 'cgkim@naver.com',	'tel' => '010-2798-2798',	'type' => '특수효과',	'introduce' => '굉장합니다.',	'stage_name' => '김선붕',
          // 'gender' => 'm',	'height' => 180,	'weight' => 69,	'local' => '서울특별시',	'career' => '별에서온그대'],
          // ['user_type'=>'개인',	'id' => 'sid34',	'password' => bcrypt(123456),	'name' => '김태수',	'birth' => 19980525,	'email' => 'taecg@gmail.com',	'tel' => '010-2456-2456',	'type' => '특수효과',	'introduce' => '깜짝놀랄걸요',	'stage_name' => '김태수',
          // 'gender' => 'm',	'height' => 174,	'weight' => 64,	'local' => '서울특별시',	'career' => '마음의 소리'],
          // ['user_type'=>'개인',	'id' => 'aid6',	'password' => bcrypt(123456),	'name' => '이세실',	'birth' => 19920422,	'email' => 'cecil@naver.com',	'tel' => '010-9999-9988',	'type' => '배우',	'introduce' => '신인 배우입니다.',	'stage_name' => '이세실',
          // 'gender' => 'w',	'height' => 169,	'weight' => 48,	'local' => '서울특별시',	'career' => '없음'],
          // ['user_type'=>'개인',	'id' => 'aid7',	'password' => bcrypt(123456),	'name' => '손기범',	'birth' => 19780909,	'email' => 'hand123@naver.com',	'tel' => '010-9988-8888',	'type' => '배우',	'introduce' => '스턴트맨',	'stage_name' => '스턴트킴',
          // 'gender' => 'm',	'height' => 177,	'weight' => 68,	'local' => '경기도 오산',	'career' => '시크릿가든'],
          // ['user_type'=>'개인',	'id' => 'aid8',	'password' => bcrypt(123456),	'name' => '이장수',	'birth' => 19780506,	'email' => 'jangsu@naver.com',	'tel' => '010-8877-7788',	'type' => '배우',	'introduce' => '멋진연기보여드리겠습니다.',	'stage_name' => '장수현',
          // 'gender' => 'm',	'height' => 189,	'weight' => 72,	'local' => '경기도 안산',	'career' => '선물'],
          // ['user_type'=>'개인',	'id' => 'aid9',	'password' => bcrypt(123456),	'name' => '고현정',	'birth' => 19880605,	'email' => '321go@naver.com',	'tel' => '010-8844-4477',	'type' => '배우',	'introduce' => '청순미 섹시미 다 가능합니다.',	'stage_name' => '유진',
          // 'gender' => 'w',	'height' => 167,	'weight' => 45,	'local' => '경기도 용인',	'career' => '뉴하트'],
          // ['user_type'=>'개인',	'id' => 'aid10',	'password' => bcrypt(123456),	'name' => '김기성',	'birth' => 19900601,	'email' => 'kica157@naver.com',	'tel' => '010-8282-8383',	'type' => '배우',	'introduce' => '연기경험은 없지만 잘 할 수 있어요',	'stage_name' => '배기성',
          // 'gender' => 'm',	'height' => 195,	'weight' => 75,	'local' => '경기도 광주',	'career' => '없음'],
          // ['user_type'=>'개인',	'id' => 'aid11',	'password' => bcrypt(123456),	'name' => '조현재',	'birth' => 19950406,	'email' => 'nowjo@naver.com',	'tel' => '010-8745-7649',	'type' => '배우',	'introduce' => '하늘에서 떨어진 신인배우',	'stage_name' => '조현재',
          // 'gender' => 'm',	'height' => 183,	'weight' => 69,	'local' => '경기도 김포',	'career' => '도깨비'],
          // ['user_type'=>'개인',	'id' => 'sid35',	'password' => bcrypt(123456),	'name' => '이회창',	'birth' => 19770709,	'email' => 'chang@gmail.com',	'tel' => '010-7777-7744',	'type' => '투자',	'introduce' => '투자자입니다.',	'stage_name' => '이회창',
          // 'gender' => 'm',	'height' => 168,	'weight' => 69,	'local' => '서울특별시',	'career' => '응답하라1997'],
          // ['user_type'=>'개인',	'id' => 'sid36',	'password' => bcrypt(123456),	'name' => '홍전일',	'birth' => 19780823,	'email' => 'honghong22@gmail.com',	'tel' => '010-7777-7733',	'type' => '연출',	'introduce' => '연출합니다.',	'stage_name' => '홍전일',
          // 'gender' => 'm',	'height' => 166,	'weight' => 65,	'local' => '서울특별시',	'career' => '피고인'],
          // ['user_type'=>'개인',	'id' => 'sid37',	'password' => bcrypt(123456),	'name' => '감동식',	'birth' => 19740628,	'email' => 'kams@gmail.com',	'tel' => '010-7777-7766',	'type' => '연출',	'introduce' => '예술적인 연출 보여드립니다.',	'stage_name' => '감동식',
          // 'gender' => 'm',	'height' => 175,	'weight' => 70,	'local' => '서울특별시',	'career' => '응답하라1997'],
          // ['user_type'=>'개인',	'id' => 'sid38',	'password' => bcrypt(123456),	'name' => '심수창',	'birth' => 19710408,	'email' => 'simsuchang@gmail.com',	'tel' => '010-7777-7755',	'type' => '분장',	'introduce' => '분장 정말 잘합니다.',	'stage_name' => '심수창',
          // 'gender' => 'w',	'height' => 173,	'weight' => 52,	'local' => '서울특별시',	'career' => '뉴하트'],
          // ['user_type'=>'개인',	'id' => 'sid39',	'password' => bcrypt(123456),	'name' => '원자현',	'birth' => 19640730,	'email' => '1jahyun@gmail.com',	'tel' => '010-7777-7711',	'type' => '분장',	'introduce' => '기가 막힌 분장을 보여드립니다.',	'stage_name' => '원자현',
          // 'gender' => 'w',	'height' => 162,	'weight' => 49,	'local' => '서울특별시',	'career' => '선덕여왕'],
          // ['user_type'=>'개인',	'id' => 'aid12',	'password' => bcrypt(123456),	'name' => '남민수',	'birth' => 19900909,	'email' => 'man1667@gmail.com',	'tel' => '010-8888-7878',	'type' => '배우',	'introduce' => '단역이 먼지 보여드립니다.',	'stage_name' => '남단역',
          // 'gender' => 'm',	'height' => 175,	'weight' => 65,	'local' => '서울특별시',	'career' => '연개소문'],
          // ['user_type'=>'개인',	'id' => 'aid13',	'password' => bcrypt(123456),	'name' => '여다혜',	'birth' => 19901212,	'email' => 'girl13@naver.com',	'tel' => '010-8899-9945',	'type' => '배우',	'introduce' => '자연스러움 그자체',	'stage_name' => '여단역',
          // 'gender' => 'w',	'height' => 159,	'weight' => 46,	'local' => '경기도 부천',	'career' => '피노키오'],
          // ['user_type'=>'개인',	'id' => 'aid14',	'password' => bcrypt(123456),	'name' => '지상수',	'birth' => 19911111,	'email' => 'walk123@gmail.com',	'tel' => '010-8524-8524',	'type' => '배우',	'introduce' => '지나가는 행인의 역할은 제게',	'stage_name' => '지나행',
          // 'gender' => 'm',	'height' => 172,	'weight' => 63,	'local' => '경기도 안산',	'career' => '시크릿가든'],
          // ['user_type'=>'개인',	'id' => 'aid15',	'password' => bcrypt(123456),	'name' => '나구현',	'birth' => 19911225,	'email' => 'watashi@gmail.com',	'tel' => '010-8686-8696',	'type' => '배우',	'introduce' => '실제알바도 나 연기알바도 나',	'stage_name' => '나알바',
          // 'gender' => 'w',	'height' => 166,	'weight' => 48,	'local' => '서울특별시',	'career' => '없음'],
          // ['user_type'=>'개인',	'id' => 'aid16',	'password' => bcrypt(123456),	'name' => '손수선',	'birth' => 19951011,	'email' => 'handteacher@naver.com',	'tel' => '010-8787-8787',	'type' => '배우',	'introduce' => '선생님 역할 정말 잘합니다.',	'stage_name' => '손선생',
          // 'gender' => 'w',	'height' => 170,	'weight' => 52,	'local' => '경기도 인천',	'career' => '학교'],
          // ['user_type'=>'개인',	'id' => 'aid17',	'password' => bcrypt(123456),	'name' => '지호선',	'birth' => 19870707,	'email' => 'gstar777@gmail.com',	'tel' => '010-8666-8666',	'type' => '배우',	'introduce' => '제가 바로 스타아니겠습니까?',	'stage_name' => '지스타',
          // 'gender' => 'm',	'height' => 185,	'weight' => 73,	'local' => '서울특별시',	'career' => '드림하이'],
          // ['user_type'=>'개인',	'id' => 'aid18',	'password' => bcrypt(123456),	'name' => '현수연',	'birth' => 19880828,	'email' => 'water7535@naver.com',	'tel' => '010-8784-8784',	'type' => '배우',	'introduce' => '현재진행중인 스타 현진입니다.',	'stage_name' => '현진',
          // 'gender' => 'm',	'height' => 191,	'weight' => 63,	'local' => '경기도 과천',	'career' => '별에서온그대'],
          // ['user_type'=>'개인',	'id' => 'sid40',	'password' => bcrypt(123456),	'name' => '천시현',	'birth' => 19900105,	'email' => 'skystart645@gmail.com',	'tel' => '010-2000-2000',	'type' => '작가',	'introduce' => '신인작가입니다.',	'stage_name' => '천시현',
          // 'gender' => 'w',	'height' => 155,	'weight' => 40,	'local' => '서울특별시',	'career' => '없음'],
          // ['user_type'=>'개인',	'id' => 'sid41',	'password' => bcrypt(123456),	'name' => '김시주',	'birth' => 19930608,	'email' => 'sijusiju7878@gmail.com',	'tel' => '010-2000-2001',	'type' => '작가',	'introduce' => '재밌는 작품 보여드릴게요',	'stage_name' => '김시주',
          // 'gender' => 'w',	'height' => 158,	'weight' => 46,	'local' => '서울특별시',	'career' => '영화는 영화다'],
          // ['user_type'=>'개인',	'id' => 'sid42',	'password' => bcrypt(123456),	'name' => '조자현',	'birth' => 19850507,	'email' => 'jojojaja@naver.com',	'tel' => '010-2000-2002',	'type' => '작가',	'introduce' => '지금까지 없었던 작품 보여드리겠습니다.',	'stage_name' => '조자현',
          // 'gender' => 'w',	'height' => 152,	'weight' => 45,	'local' => '경기도 과천',	'career' => '괴물'],
          // ['user_type'=>'개인',	'id' => 'sid43',	'password' => bcrypt(123456),	'name' => '김수지',	'birth' => 19850406,	'email' => 'waterground@gmail.com',	'tel' => '010-2000-2003',	'type' => '작가',	'introduce' => '연애드라마 전문',	'stage_name' => '김수지',
          // 'gender' => 'w',	'height' => 159,	'weight' => 50,	'local' => '경기도 안산',	'career' => '달콤했던 그사람'],
          // ['user_type'=>'개인',	'id' => 'sid44',	'password' => bcrypt(123456),	'name' => '김소현',	'birth' => 19840630,	'email' => 'little675@naver.com',	'tel' => '010-2000-2004',	'type' => '작가',	'introduce' => '스릴러 전문입니다.',	'stage_name' => '김소현',
          // 'gender' => 'w',	'height' => 160,	'weight' => 52,	'local' => '경기도 수원',	'career' => '범죄자'],
          // ['user_type'=>'개인',	'id' => 'sid45',	'password' => bcrypt(123456),	'name' => '이수혁',	'birth' => 19860205,	'email' => 'sulee583@naver.com',	'tel' => '010-2000-2005',	'type' => '작가',	'introduce' => '글에서도 느껴지는 액션을 보여드리겠습니다.',	'stage_name' => '이수혁',
          // 'gender' => 'm',	'height' => 173,	'weight' => 70,	'local' => '경기도 부산',	'career' => '취업은 영진'],
          // ['user_type'=>'개인',	'id' => 'sid46',	'password' => bcrypt(123456),	'name' => '장조현',	'birth' => 19770506,	'email' => 'wkdwhgus1258@gmail.com',	'tel' => '010-2000-2006',	'type' => '작가',	'introduce' => '집에서 소소하게 씁니다.',	'stage_name' => '장조현',
          // 'gender' => 'm',	'height' => 174,	'weight' => 72,	'local' => '경기도 김포',	'career' => '오늘도 소나무에서'],
          // ['user_type'=>'개인',	'id' => 'sid47',	'password' => bcrypt(123456),	'name' => '백정현',	'birth' => 19870606,	'email' => 'white57389@gmail.com',	'tel' => '010-2000-2007',	'type' => '작가',	'introduce' => '무슨 장르든 정말 잘써요',	'stage_name' => '백정현',
          // 'gender' => 'w',	'height' => 162,	'weight' => 50,	'local' => '경기도 대구',	'career' => '여자들아'],
          // ['user_type'=>'개인',	'id' => 'sid48',	'password' => bcrypt(123456),	'name' => '지수진',	'birth' => 19900405,	'email' => 'jisujin85693@gmail.com',	'tel' => '010-2000-2008',	'type' => '작가',	'introduce' => '불러만 주세요',	'stage_name' => '지수진',
          // 'gender' => 'w',	'height' => 163,	'weight' => 55,	'local' => '경기도 인천',	'career' => '없음'],
          // ['user_type'=>'개인',	'id' => 'sid49',	'password' => bcrypt(123456),	'name' => '고수혁',	'birth' => 19690609,	'email' => 'master2883@naver.com',	'tel' => '010-2000-2009',	'type' => '작가',	'introduce' => '누구도 보지 못한 작품 보여드릴게요',	'stage_name' => '고수혁',
          // 'gender' => 'm',	'height' => 169,	'weight' => 62,	'local' => '광주광역시',	'career' => '의리가 멋있잖아'],
          // ['user_type'=>'개인',	'id' => 'sid50',	'password' => bcrypt(123456),	'name' => '반정욱',	'birth' => 19941022,	'email' => 'ban182@gmail.com',	'tel' => '010-2000-2010',	'type' => '작가',	'introduce' => '예술이 무엇인지 알려드리겠습니다.',	'stage_name' => '반정욱',
          // 'gender' => 'm',	'height' => 178,	'weight' => 71,	'local' => '경기도 광주',	'career' => '세상에 반은'],
          // ['user_type'=>'개인',	'id' => 'sid51',	'password' => bcrypt(123456),	'name' => '마영현',	'birth' => 19840505,	'email' => 'mazero@naver.com',	'tel' => '010-2000-2011',	'type' => '작가',	'introduce' => '나는 작가다',	'stage_name' => '마영현',
          // 'gender' => 'w',	'height' => 166,	'weight' => 52,	'local' => '경기도 용인',	'career' => '이별쯤은'],
          // ['user_type'=>'개인',	'id' => 'aid19',	'password' => bcrypt(123456),	'name' => '아전수',	'birth' => 20110505,	'email' => 'child119@naver.com',	'tel' => '010-8888-0505',	'type' => '배우',	'introduce' => '아역배우입니다.',	'stage_name' => '아동영',
          // 'gender' => 'm',	'height' => 128,	'weight' => 23,	'local' => '서울특별시',	'career' => '없음'],

          ['user_type'=>'개인',	'id' => 'aid1',	'password' => bcrypt(123456),	'name' => '平田 正',	'birth' => 19810728,	'email' => 'insung@gmail.com',	'tel' => '010-7897-7987',	'type' => '俳優',	'introduce' => 'よろしくお願いします',
          'stage_name' => '平田 正',	'gender' => 'm',	'height' => 186,	'weight' => 76,	'local' => 'hyogo',	'career' => '新撰組'],
          ['user_type'=>'개인',	'id' => 'aid2',	'password' => bcrypt(123456),	'name' => '安部 浩一',	'birth' => 19771110,	'email' => '1bin@naver.com',	'tel' => '010-1111-1111',	'type' => '俳優',	'introduce' => 'よろしくお願いします',
          'stage_name' => '安部 浩一',	'gender' => 'm',	'height' => 178,	'weight' => 65,	'local' => 'tokyo',	'career' => 'Space Brothers'],
          ['user_type'=>'개인',	'id' => 'aid3',	'password' => bcrypt(123456),	'name' => '吉野 進',	'birth' => 19700104,	'email' => 'yousun@gmail.com',	'tel' => '010-1231-1231',	'type' => '俳優',	'introduce' => 'よろしくお願いします',
          'stage_name' => '吉野 進',	'gender' => 'm',	'height' => 174,	'weight' => 65,	'local' => 'tokyo',	'career' => '義経'],
          ['user_type'=>'개인',	'id' => 'aid4',	'password' => bcrypt(123456),	'name' => '森田 美樹',	'birth' => 19800329,	'email' => 'taehee@naver.com',	'tel' => '010-1233-1233',	'type' => '俳優',	'introduce' => 'よろしくお願いします',
          'stage_name' => '森田 美樹',	'gender' => 'w',	'height' => 162,	'weight' => 45,	'local' => 'tokyo',	'career' => '白い巨塔'],
          ['user_type'=>'개인',	'id' => 'aid5',	'password' => bcrypt(123456),	'name' => '中川 千明',	'birth' => 19900424,	'email' => 'lee@gmail.com',	'tel' => '010-1212-1212',	'type' => '俳優',	'introduce' => 'よろしくお願いします',
          'stage_name' => '中川 千明',	'gender' => 'w',	'height' => 166,	'weight' => 48,	'local' => 'nagoya',	'career' => '白い巨塔'],
          ['user_type'=>'개인',	'id' => 'sid1',	'password' => bcrypt(123456),	'name' => '後藤 弘行',	'birth' => 19630823,	'email' => 'chan@gmail.com',	'tel' => '010-5555-5555',	'type' => '撮影',	'introduce' => '頑張ります',
          'stage_name' => '後藤 弘行',	'gender' => 'm',	'height' => 175,	'weight' => 70,	'local' => 'nagoya',	'career' => 'ザ世界仰天ニュース'],
          ['user_type'=>'개인',	'id' => 'sid2',	'password' => bcrypt(123456),	'name' => '渡邉 裕一郎',	'birth' => 19720505,	'email' => 'starkarakita@naver.com',	'tel' => '010-5556-5556',	'type' => '撮影',	'introduce' => '頑張ります',
          'stage_name' => '渡邉 裕一郎',	'gender' => 'm',	'height' => 175,	'weight' => 70,	'local' => 'fukuoka',	'career' => '青い鳥'],
          ['user_type'=>'개인',	'id' => 'sid3',	'password' => bcrypt(123456),	'name' => '岡本 基',	'birth' => 19770407,	'email' => 'jogam@naver.com',	'tel' => '010-3333-3333',	'type' => '照明',	'introduce' => '頑張ります',
          'stage_name' => '岡本 基',	'gender' => 'm',	'height' => 178,	'weight' => 85,	'local' => 'tokyo',	'career' => 'ウルトラマンガイア'],
          ['user_type'=>'개인',	'id' => 'sid4',	'password' => bcrypt(123456),	'name' => '岸 亮介',	'birth' => 19900505,	'email' => 'jmlee@gmail.com',	'tel' => '010-3334-3334',	'type' => '照明',	'introduce' => '頑張ります',
          'stage_name' => '岸 亮介',	'gender' => 'm',	'height' => 191,	'weight' => 86,	'local' => 'akita',	'career' => '無'],
          ['user_type'=>'개인',	'id' => 'sid5',	'password' => bcrypt(123456),	'name' => '林田 美佳',	'birth' => 19850806,	'email' => 'sch@naver.com',	'tel' => '010-1230-3651',	'type' => 'スケジュール',	'introduce' => '頑張ります',
          'stage_name' => '林田 美佳',	'gender' => 'w',	'height' => 162,	'weight' => 45,	'local' => 'osaka',	'career' => '高校教師'],
          ['user_type'=>'개인',	'id' => 'sid6',	'password' => bcrypt(123456),	'name' => '南 健人',	'birth' => 19830507,	'email' => 'sch2@naver.com',	'tel' => '010-3651-1230',	'type' => 'スケジュール',	'introduce' => '頑張ります',
          'stage_name' => '南 健人',	'gender' => 'm',	'height' => 170,	'weight' => 75,	'local' => 'gunma',	'career' => '最後の家族'],
          ['user_type'=>'개인',	'id' => 'sid7',	'password' => bcrypt(123456),	'name' => '櫻井 俊哉',	'birth' => 19810501,	'email' => 'jmkim@naver.com',	'tel' => '010-1911-1911',	'type' => '照明',	'introduce' => '頑張ります',
          'stage_name' => '櫻井 俊哉',	'gender' => 'm',	'height' => 169,	'weight' => 65,	'local' => 'tokyo',	'career' => 'ニコニコ少女'],
          ['user_type'=>'개인',	'id' => 'sid8',	'password' => bcrypt(123456),	'name' => '丹羽 昇',	'birth' => 19811212,	'email' => 'jmjang@gmail.com',	'tel' => '010-5885-5885',	'type' => '照明',	'introduce' => '頑張ります',
          'stage_name' => '丹羽 昇',	'gender' => 'm',	'height' => 172,	'weight' => 70,	'local' => 'ehime',	'career' => 'BS時代劇 薄桜記'],
          ['user_type'=>'개인',	'id' => 'sid9',	'password' => bcrypt(123456),	'name' => '本田 厚',	'birth' => 19881216,	'email' => 'jorec@naver.com',	'tel' => '010-1666-6661',	'type' => '録音',	'introduce' => '頑張ります',
          'stage_name' => '本田 厚',	'gender' => 'm',	'height' => 189,	'weight' => 75,	'local' => 'tokyo',	'career' => 'ああ嫁さん'],
          ['user_type'=>'개인',	'id' => 'sid10',	'password' => bcrypt(123456),	'name' => '横田 達郎',	'birth' => 19800501,	'email' => 'jijakka@naver.com',	'tel' => '010-2236-2246',	'type' => '作家',	'introduce' => '頑張ります',
          'stage_name' => '横田 達郎',	'gender' => 'm',	'height' => 180,	'weight' => 73,	'local' => 'tokyo',	'career' => 'エンジン'],
          ['user_type'=>'개인',	'id' => 'sid11',	'password' => bcrypt(123456),	'name' => '加藤 あやめ',	'birth' => 19780603,	'email' => 'jklee@naver.com',	'tel' => '010-2224-2256',	'type' => '作家',	'introduce' => '頑張ります',
          'stage_name' => '加藤 あやめ',	'gender' => 'w',	'height' => 169,	'weight' => 50,	'local' => 'fukuoka',	'career' => 'スローダンス'],
          ['user_type'=>'개인',	'id' => 'sid12',	'password' => bcrypt(123456),	'name' => '野村 智大',	'birth' => 19770808,	'email' => 'jkkim@naver.com',	'tel' => '010-2223-2223',	'type' => '作家',	'introduce' => '頑張ります',
          'stage_name' => '野村 智大',	'gender' => 'm',	'height' => 177,	'weight' => 70,	'local' => 'chiba',	'career' => 'ストレートニュース'],
          ['user_type'=>'개인',	'id' => 'sid13',	'password' => bcrypt(123456),	'name' => '小川 愛莉',	'birth' => 19880906,	'email' => 'jojakka@gmail.com',	'tel' => '010-2222-2222',	'type' => '作家',	'introduce' => '頑張ります',
          'stage_name' => '小川 愛莉',	'gender' => 'w',	'height' => 155,	'weight' => 44,	'local' => 'osaka',	'career' => 'ハガネの女 season2'],
          ['user_type'=>'개인',	'id' => 'sid14',	'password' => bcrypt(123456),	'name' => '丸山 泰三',	'birth' => 19750530,	'email' => 'nokkam@naver.com',	'tel' => '010-5555-5522',	'type' => '録音',	'introduce' => '頑張ります',
          'stage_name' => '丸山 泰三',	'gender' => 'm',	'height' => 169,	'weight' => 70,	'local' => 'tokyo',	'career' => '下町ロケット'],
          ['user_type'=>'개인',	'id' => 'sid15',	'password' => bcrypt(123456),	'name' => '三輪 いずみ',	'birth' => 19900108,	'email' => 'sopum@naver.com',	'tel' => '010-1133-1945',	'type' => '録音',	'introduce' => '頑張ります',
          'stage_name' => '三輪 いずみ',	'gender' => 'w',	'height' => 158,	'weight' => 53,	'local' => 'tokyo',	'career' => 'アイムホーム'],
          ['user_type'=>'개인',	'id' => 'sid16',	'password' => bcrypt(123456),	'name' => '北村 里子',	'birth' => 19781001,	'email' => 'misulkam1@gmail.com',	'tel' => '010-5566-5598',	'type' => '美術',	'introduce' => '頑張ります',
          'stage_name' => '北村 里子',	'gender' => 'w',	'height' => 155,	'weight' => 52,	'local' => 'tokyo',	'career' => 'DOCTORS3　最強の名医'],
          ['user_type'=>'개인',	'id' => 'sid17',	'password' => bcrypt(123456),	'name' => '西川 祐',	'birth' => 19900506,	'email' => 'misul324@naver.com',	'tel' => '010-1218-1218',	'type' => '美術',	'introduce' => '頑張ります',
          'stage_name' => '西川 祐',	'gender' => 'm',	'height' => 166,	'weight' => 55,	'local' => 'nagoya',	'career' => 'デスノート'],
          ['user_type'=>'개인',	'id' => 'sid18',	'password' => bcrypt(123456),	'name' => '工藤 龍之介',	'birth' => 19821111,	'email' => 'mukam@naver.com',	'tel' => '010-5959-5959',	'type' => '美術',	'introduce' => '頑張ります',
          'stage_name' => '工藤 龍之介',	'gender' => 'm',	'height' => 199,	'weight' => 75,	'local' => 'nagoya',	'career' => '花咲舞が黙ってない'],
          ['user_type'=>'개인',	'id' => 'sid19',	'password' => bcrypt(123456),	'name' => '松島 幸司',	'birth' => 19880105,	'email' => 'chulchul@naver.com',	'tel' => '010-1155-5511',	'type' => '演出',	'introduce' => '頑張ります',
          'stage_name' => '松島 幸司',	'gender' => 'm',	'height' => 186,	'weight' => 77,	'local' => 'fukuoka',	'career' => '銭の戦争'],
          ['user_type'=>'개인',	'id' => 'sid20',	'password' => bcrypt(123456),	'name' => '川口 啓之',	'birth' => 19970630,	'email' => 'yearlee@gmail.com',	'tel' => '010-1122-2211',	'type' => '演出',	'introduce' => '頑張ります',
          'stage_name' => '川口 啓之',	'gender' => 'm',	'height' => 177,	'weight' => 76,	'local' => 'tokyo',	'career' => '偽装の夫婦'],
          ['user_type'=>'개인',	'id' => 'sid21',	'password' => bcrypt(123456),	'name' => '栗田 祐司',	'birth' => 19950405,	'email' => 'jobs@naver.com',	'tel' => '010-1444-4422',	'type' => '演出',	'introduce' => '頑張ります',
          'stage_name' => '栗田 祐司',	'gender' => 'm',	'height' => 175,	'weight' => 74,	'local' => 'akita',	'career' => '花より男子2（リターンズ）'],
          ['user_type'=>'개인',	'id' => 'sid22',	'password' => bcrypt(123456),	'name' => '比嘉 康之',	'birth' => 19920303,	'email' => 'fd23@gmail.com',	'tel' => '010-1239-9988',	'type' => '演出',	'introduce' => '頑張ります',
          'stage_name' => '比嘉 康之',	'gender' => 'm',	'height' => 176,	'weight' => 73,	'local' => 'osaka',	'career' => 'ごくせん　第3シリーズ'],
          ['user_type'=>'개인',	'id' => 'sid23',	'password' => bcrypt(123456),	'name' => '赤塚 博',	'birth' => 19850825,	'email' => 'houhome@gmail.com',	'tel' => '010-1222-7845',	'type' => '編集',	'introduce' => '頑張ります',
          'stage_name' => '赤塚 博',	'gender' => 'm',	'height' => 168,	'weight' => 71,	'local' => 'gunma',	'career' => 'プライド'],
          ['user_type'=>'개인',	'id' => 'sid24',	'password' => bcrypt(123456),	'name' => '濱田 正雄',	'birth' => 19900206,	'email' => 'kamera@gmail.com',	'tel' => '010-1335-3322',	'type' => '撮影',	'introduce' => '頑張ります',
          'stage_name' => '濱田 正雄',	'gender' => 'm',	'height' => 169,	'weight' => 72,	'local' => 'tokyo',	'career' => 'ハケンの品格'],
          ['user_type'=>'개인',	'id' => 'sid25',	'password' => bcrypt(123456),	'name' => '土屋 幸二',	'birth' => 19900224,	'email' => 'camera@naver.com',	'tel' => '010-1111-3333',	'type' => '撮影',	'introduce' => '頑張ります',
          'stage_name' => '土屋 幸二',	'gender' => 'm',	'height' => 175,	'weight' => 73,	'local' => 'ehime',	'career' => 'オレンジデイズ'],
          ['user_type'=>'개인',	'id' => 'sid26',	'password' => bcrypt(123456),	'name' => '安井 純也',	'birth' => 19870723,	'email' => 'music@naver.com',	'tel' => '010-1811-1814',	'type' => '音楽',	'introduce' => '頑張ります',
          'stage_name' => '安井 純也',	'gender' => 'm',	'height' => 167,	'weight' => 69,	'local' => 'tokyo',	'career' => '新撰組'],
          ['user_type'=>'개인',	'id' => 'sid27',	'password' => bcrypt(123456),	'name' => '末永 伸一',	'birth' => 19780913,	'email' => 'sound@naver.com',	'tel' => '010-1319-1919',	'type' => '音楽',	'introduce' => '頑張ります',
          'stage_name' => '末永 伸一',	'gender' => 'm',	'height' => 179,	'weight' => 68,	'local' => 'tokyo',	'career' => 'Space Brothers'],
          ['user_type'=>'개인',	'id' => 'sid28',	'password' => bcrypt(123456),	'name' => '相馬 良一',	'birth' => 19770727,	'email' => 'location@gmail.com',	'tel' => '010-2424-2424',	'type' => 'ロケーション',	'introduce' => '頑張ります',
          'stage_name' => '相馬 良一',	'gender' => 'm',	'height' => 172,	'weight' => 60,	'local' => 'tokyo',	'career' => '義経'],
          ['user_type'=>'개인',	'id' => 'sid29',	'password' => bcrypt(123456),	'name' => '小野寺 麗子',	'birth' => 19830323,	'email' => 'hairkoo@gmail.com',	'tel' => '010-5656-5655',	'type' => 'ヘア',	'introduce' => '頑張ります',
          'stage_name' => '小野寺 麗子',	'gender' => 'w',	'height' => 168,	'weight' => 53,	'local' => 'ehime',	'career' => '白い巨塔'],
          ['user_type'=>'개인',	'id' => 'sid30',	'password' => bcrypt(123456),	'name' => '福井 江美',	'birth' => 19910801,	'email' => 'hairhair@naver.com',	'tel' => '010-5955-5544',	'type' => 'ヘア',	'introduce' => '頑張ります',
          'stage_name' => '福井 江美',	'gender' => 'w',	'height' => 162,	'weight' => 50,	'local' => 'tokyo',	'career' => '白い巨塔'],
          ['user_type'=>'개인',	'id' => 'sid31',	'password' => bcrypt(123456),	'name' => '藤木 弘',	'birth' => 19690830,	'email' => 'busya@gmail.com',	'tel' => '010-2111-2525',	'type' => '運送',	'introduce' => '頑張ります',
          'stage_name' => '藤木 弘',	'gender' => 'm',	'height' => 170,	'weight' => 77,	'local' => 'tokyo',	'career' => 'ザ世界仰天ニュース'],
          ['user_type'=>'개인',	'id' => 'sid32',	'password' => bcrypt(123456),	'name' => '亀井 晋',	'birth' => 19650410,	'email' => 'fastjo@gmail.com',	'tel' => '010-2525-2424',	'type' => '運送',	'introduce' => '頑張ります',
          'stage_name' => '亀井 晋',	'gender' => 'm',	'height' => 169,	'weight' => 70,	'local' => 'fukuoka',	'career' => '青い鳥'],
          ['user_type'=>'개인',	'id' => 'sid33',	'password' => bcrypt(123456),	'name' => '岡島 啓介',	'birth' => 19890621,	'email' => 'cgkim@naver.com',	'tel' => '010-2798-2798',	'type' => '特殊効果',	'introduce' => '頑張ります',
          'stage_name' => '岡島 啓介',	'gender' => 'm',	'height' => 180,	'weight' => 69,	'local' => 'chiba',	'career' => 'ウルトラマンガイア'],
          ['user_type'=>'개인',	'id' => 'sid34',	'password' => bcrypt(123456),	'name' => '石本 健一郎',	'birth' => 19980525,	'email' => 'taecg@gmail.com',	'tel' => '010-2456-2456',	'type' => '特殊効果',	'introduce' => '頑張ります',
          'stage_name' => '石本 健一郎',	'gender' => 'm',	'height' => 174,	'weight' => 64,	'local' => 'osaka',	'career' => '無'],
          ['user_type'=>'개인',	'id' => 'aid6',	'password' => bcrypt(123456),	'name' => '川野 千里',	'birth' => 19920422,	'email' => 'cecil@naver.com',	'tel' => '010-9999-9988',	'type' => '俳優',	'introduce' => 'よろしくお願いします',
          'stage_name' => '川野 千里',	'gender' => 'w',	'height' => 169,	'weight' => 48,	'local' => 'tokyo',	'career' => '高校教師'],
          ['user_type'=>'개인',	'id' => 'aid7',	'password' => bcrypt(123456),	'name' => '合田 毅',	'birth' => 19780909,	'email' => 'hand123@naver.com',	'tel' => '010-9988-8888',	'type' => '俳優',	'introduce' => 'よろしくお願いします',
          'stage_name' => '合田 毅',	'gender' => 'm',	'height' => 177,	'weight' => 68,	'local' => 'tokyo',	'career' => '最後の家族'],
          ['user_type'=>'개인',	'id' => 'aid8',	'password' => bcrypt(123456),	'name' => '堀口 淳也',	'birth' => 19780506,	'email' => 'jangsu@naver.com',	'tel' => '010-8877-7788',	'type' => '俳優',	'introduce' => 'よろしくお願いします',
          'stage_name' => '堀口 淳也',	'gender' => 'm',	'height' => 189,	'weight' => 72,	'local' => 'tokyo',	'career' => 'ニコニコ少女'],
          ['user_type'=>'개인',	'id' => 'aid9',	'password' => bcrypt(123456),	'name' => '片岡 由実',	'birth' => 19880605,	'email' => '321go@naver.com',	'tel' => '010-8844-4477',	'type' => '俳優',	'introduce' => 'よろしくお願いします',
          'stage_name' => '片岡 由実',	'gender' => 'w',	'height' => 167,	'weight' => 45,	'local' => 'nagoya',	'career' => 'BS時代劇 薄桜記'],
          ['user_type'=>'개인',	'id' => 'aid10',	'password' => bcrypt(123456),	'name' => '湊 俊一',	'birth' => 19900601,	'email' => 'kica157@naver.com',	'tel' => '010-8282-8383',	'type' => '俳優',	'introduce' => 'よろしくお願いします',
          'stage_name' => '湊 俊一',	'gender' => 'm',	'height' => 195,	'weight' => 75,	'local' => 'nagoya',	'career' => 'ああ嫁さん'],
          ['user_type'=>'개인',	'id' => 'aid11',	'password' => bcrypt(123456),	'name' => '嶋田 公平',	'birth' => 19950406,	'email' => 'nowjo@naver.com',	'tel' => '010-8745-7649',	'type' => '俳優',	'introduce' => 'よろしくお願いします',
          'stage_name' => '嶋田 公平',	'gender' => 'm',	'height' => 183,	'weight' => 69,	'local' => 'fukuoka',	'career' => 'エンジン'],
          ['user_type'=>'개인',	'id' => 'sid35',	'password' => bcrypt(123456),	'name' => '佐伯 耕司',	'birth' => 19770709,	'email' => 'chang@gmail.com',	'tel' => '010-7777-7744',	'type' => '投資',	'introduce' => '頑張ります',
          'stage_name' => '佐伯 耕司',	'gender' => 'm',	'height' => 168,	'weight' => 69,	'local' => 'tokyo',	'career' => 'スローダンス'],
          ['user_type'=>'개인',	'id' => 'sid36',	'password' => bcrypt(123456),	'name' => '井口 厚志',	'birth' => 19780823,	'email' => 'honghong22@gmail.com',	'tel' => '010-7777-7733',	'type' => '演出',	'introduce' => '頑張ります',
          'stage_name' => '井口 厚志',	'gender' => 'm',	'height' => 166,	'weight' => 65,	'local' => 'hyogo',	'career' => 'ストレートニュース'],
          ['user_type'=>'개인',	'id' => 'sid37',	'password' => bcrypt(123456),	'name' => '柳澤 智宏',	'birth' => 19740628,	'email' => 'kams@gmail.com',	'tel' => '010-7777-7766',	'type' => '演出',	'introduce' => '頑張ります',
          'stage_name' => '柳澤 智宏',	'gender' => 'm',	'height' => 175,	'weight' => 70,	'local' => 'tokyo',	'career' => 'ハガネの女 season2'],
          ['user_type'=>'개인',	'id' => 'sid38',	'password' => bcrypt(123456),	'name' => '田邉 菜摘',	'birth' => 19710408,	'email' => 'simsuchang@gmail.com',	'tel' => '010-7777-7755',	'type' => '扮装',	'introduce' => '頑張ります',
          'stage_name' => '田邉 菜摘',	'gender' => 'w',	'height' => 173,	'weight' => 52,	'local' => 'tokyo',	'career' => '下町ロケット'],
          ['user_type'=>'개인',	'id' => 'sid39',	'password' => bcrypt(123456),	'name' => '原 絹代',	'birth' => 19640730,	'email' => '1jahyun@gmail.com',	'tel' => '010-7777-7711',	'type' => '扮装',	'introduce' => '頑張ります',
          'stage_name' => '原 絹代',	'gender' => 'w',	'height' => 162,	'weight' => 49,	'local' => 'tokyo',	'career' => 'アイムホーム'],
          ['user_type'=>'개인',	'id' => 'aid12',	'password' => bcrypt(123456),	'name' => '小嶋 雄',	'birth' => 19900909,	'email' => 'man1667@gmail.com',	'tel' => '010-8888-7878',	'type' => '俳優',	'introduce' => 'よろしくお願いします',
          'stage_name' => '小嶋 雄',	'gender' => 'm',	'height' => 175,	'weight' => 65,	'local' => 'nagoya',	'career' => 'DOCTORS3　最強の名医'],
          ['user_type'=>'개인',	'id' => 'aid13',	'password' => bcrypt(123456),	'name' => '梅原 愛 ',	'birth' => 19901212,	'email' => 'girl13@naver.com',	'tel' => '010-8899-9945',	'type' => '俳優',	'introduce' => 'よろしくお願いします',
          'stage_name' => '梅原 愛 ',	'gender' => 'w',	'height' => 159,	'weight' => 46,	'local' => 'nagoya',	'career' => 'デスノート'],
          ['user_type'=>'개인',	'id' => 'aid14',	'password' => bcrypt(123456),	'name' => '中塚 英雄',	'birth' => 19911111,	'email' => 'walk123@gmail.com',	'tel' => '010-8524-8524',	'type' => '俳優',	'introduce' => 'よろしくお願いします',
          'stage_name' => '中塚 英雄',	'gender' => 'm',	'height' => 172,	'weight' => 63,	'local' => 'fukuoka',	'career' => '花咲舞が黙ってない'],
          ['user_type'=>'개인',	'id' => 'aid15',	'password' => bcrypt(123456),	'name' => '松山 美佐',	'birth' => 19911225,	'email' => 'watashi@gmail.com',	'tel' => '010-8686-8696',	'type' => '俳優',	'introduce' => 'よろしくお願いします',
          'stage_name' => '松山 美佐',	'gender' => 'w',	'height' => 166,	'weight' => 48,	'local' => 'tokyo',	'career' => '銭の戦争'],
          ['user_type'=>'개인',	'id' => 'aid16',	'password' => bcrypt(123456),	'name' => '阿部 有希',	'birth' => 19951011,	'email' => 'handteacher@naver.com',	'tel' => '010-8787-8787',	'type' => '俳優',	'introduce' => 'よろしくお願いします',
          'stage_name' => '阿部 有希',	'gender' => 'w',	'height' => 170,	'weight' => 52,	'local' => 'akita',	'career' => '偽装の夫婦'],
          ['user_type'=>'개인',	'id' => 'aid17',	'password' => bcrypt(123456),	'name' => '島村 真樹',	'birth' => 19870707,	'email' => 'gstar777@gmail.com',	'tel' => '010-8666-8666',	'type' => '俳優',	'introduce' => 'よろしくお願いします',
          'stage_name' => '島村 真樹',	'gender' => 'm',	'height' => 185,	'weight' => 73,	'local' => 'osaka',	'career' => '花より男子2（リターンズ）'],
          ['user_type'=>'개인',	'id' => 'aid18',	'password' => bcrypt(123456),	'name' => '細野 竜一',	'birth' => 19880828,	'email' => 'water7535@naver.com',	'tel' => '010-8784-8784',	'type' => '俳優',	'introduce' => 'よろしくお願いします',
          'stage_name' => '細野 竜一',	'gender' => 'm',	'height' => 191,	'weight' => 63,	'local' => 'gunma',	'career' => 'ごくせん　第3シリーズ'],
          ['user_type'=>'개인',	'id' => 'sid40',	'password' => bcrypt(123456),	'name' => '富田 真樹',	'birth' => 19900105,	'email' => 'skystart645@gmail.com',	'tel' => '010-2000-2000',	'type' => '作家',	'introduce' => '頑張ります',
          'stage_name' => '富田 真樹',	'gender' => 'w',	'height' => 155,	'weight' => 40,	'local' => 'tokyo',	'career' => 'プライド'],
          ['user_type'=>'개인',	'id' => 'sid41',	'password' => bcrypt(123456),	'name' => '王 千紘',	'birth' => 19930608,	'email' => 'sijusiju7878@gmail.com',	'tel' => '010-2000-2001',	'type' => '作家',	'introduce' => '頑張ります',
          'stage_name' => '王 千紘',	'gender' => 'w',	'height' => 158,	'weight' => 46,	'local' => 'ehime',	'career' => 'ハケンの品格'],
          ['user_type'=>'개인',	'id' => 'sid42',	'password' => bcrypt(123456),	'name' => '本間 由記',	'birth' => 19850507,	'email' => 'jojojaja@naver.com',	'tel' => '010-2000-2002',	'type' => '作家',	'introduce' => '頑張ります',	
          'stage_name' => '本間 由記',	'gender' => 'w',	'height' => 152,	'weight' => 45,	'local' => 'tokyo',	'career' => 'オレンジデイズ'],
          ['user_type'=>'개인',	'id' => 'sid43',	'password' => bcrypt(123456),	'name' => '馬場 ともこ',	'birth' => 19850406,	'email' => 'waterground@gmail.com',	'tel' => '010-2000-2003',	'type' => '作家',	'introduce' => '頑張ります',
          'stage_name' => '馬場 ともこ',	'gender' => 'w',	'height' => 159,	'weight' => 50,	'local' => 'tokyo',	'career' => '新撰組'],
          ['user_type'=>'개인',	'id' => 'sid44',	'password' => bcrypt(123456),	'name' => '丸山 牧',	'birth' => 19840630,	'email' => 'little675@naver.com',	'tel' => '010-2000-2004',	'type' => '作家',	'introduce' => '頑張ります',
          'stage_name' => '丸山 牧',	'gender' => 'w',	'height' => 160,	'weight' => 52,	'local' => 'fukuoka',	'career' => 'Space Brothers'],
          ['user_type'=>'개인',	'id' => 'sid45',	'password' => bcrypt(123456),	'name' => '阿久津 一平',	'birth' => 19860205,	'email' => 'sulee583@naver.com',	'tel' => '010-2000-2005',	'type' => '作家',	'introduce' => '頑張ります',
          'stage_name' => '阿久津 一平',	'gender' => 'm',	'height' => 173,	'weight' => 70,	'local' => 'chiba',	'career' => '義経'],
          ['user_type'=>'개인',	'id' => 'sid46',	'password' => bcrypt(123456),	'name' => '須賀 歩',	'birth' => 19770506,	'email' => 'wkdwhgus1258@gmail.com',	'tel' => '010-2000-2006',	'type' => '作家',	'introduce' => '頑張ります',
          'stage_name' => '須賀 歩',	'gender' => 'm',	'height' => 174,	'weight' => 72,	'local' => 'osaka',	'career' => '白い巨塔'],
          ['user_type'=>'개인',	'id' => 'sid47',	'password' => bcrypt(123456),	'name' => '永野 有希',	'birth' => 19870606,	'email' => 'white57389@gmail.com',	'tel' => '010-2000-2007',	'type' => '作家',	'introduce' => '頑張ります',
          'stage_name' => '永野 有希',	'gender' => 'w',	'height' => 162,	'weight' => 50,	'local' => 'tokyo',	'career' => '白い巨塔'],
          ['user_type'=>'개인',	'id' => 'sid48',	'password' => bcrypt(123456),	'name' => '真鍋 莉奈',	'birth' => 19900405,	'email' => 'jisujin85693@gmail.com',	'tel' => '010-2000-2008',	'type' => '作家',	'introduce' => '頑張ります',
          'stage_name' => '真鍋 莉奈',	'gender' => 'w',	'height' => 163,	'weight' => 55,	'local' => 'tokyo',	'career' => 'ザ世界仰天ニュース'],
          ['user_type'=>'개인',	'id' => 'sid49',	'password' => bcrypt(123456),	'name' => '秋葉 和広',	'birth' => 19690609,	'email' => 'master2883@naver.com',	'tel' => '010-2000-2009',	'type' => '作家',	'introduce' => '頑張ります',
          'stage_name' => '秋葉 和広',	'gender' => 'm',	'height' => 169,	'weight' => 62,	'local' => 'tokyo',	'career' => '青い鳥'],
          ['user_type'=>'개인',	'id' => 'sid50',	'password' => bcrypt(123456),	'name' => '藤崎 裕史',	'birth' => 19941022,	'email' => 'ban182@gmail.com',	'tel' => '010-2000-2010',	'type' => '作家',	'introduce' => '頑張ります',
          'stage_name' => '藤崎 裕史',	'gender' => 'm',	'height' => 178,	'weight' => 71,	'local' => 'nagoya',	'career' => 'ウルトラマンガイア'],
          ['user_type'=>'개인',	'id' => 'sid51',	'password' => bcrypt(123456),	'name' => '江口 あみ',	'birth' => 19840505,	'email' => 'mazero@naver.com',	'tel' => '010-2000-2011',	'type' => '作家',	'introduce' => '頑張ります',
          'stage_name' => '江口 あみ',	'gender' => 'w',	'height' => 166,	'weight' => 52,	'local' => 'nagoya',	'career' => '無'],
          ['user_type'=>'개인',	'id' => 'aid19',	'password' => bcrypt(123456),	'name' => '真鍋 勝利',	'birth' => 20110505,	'email' => 'child119@naver.com',	'tel' => '010-8888-0505',	'type' => '俳優',	'introduce' => 'よろしくお願いします',
          'stage_name' => '真鍋 勝利',	'gender' => 'm',	'height' => 128,	'weight' => 23,	'local' => 'fukuoka',	'career' => '高校教師'],


        ];

        DB::table('users')->insert($users);

    }
}
